- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.visonic_mct_340_e_0b121b78_1_1280', 'on') }}"
      availability_template: "{{ states('binary_sensor.visonic_mct_340_e_0b121b78_1_1280') != 'unavailable' }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.fortrezz_mimolite_switch
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.fortrezz_mimolite_switch
