- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.visonic_mct_340_e_781b120b_ias_zone', 'on') }}"
      availability_template: "{{ states('binary_sensor.visonic_mct_340_e_781b120b_ias_zone') != 'unavailable' }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.digital_or_analog_voltage_input_and_or_dry_contact_relay
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.digital_or_analog_voltage_input_and_or_dry_contact_relay
