- alias: Jim is Home
  trigger:
    platform: state
    entity_id: device_tracker.bt_jim_cell
    from: 'not_home'
    to: 'home'
  action:
    service: tts.google_say
    data:
      entity_id: media_player.living_room_home
      message: "Welcome home, Jim"

- alias: Erica is Home
  trigger:
    platform: state
    entity_id: device_tracker.bt_erica_cell
    from: 'not_home'
    to: 'home'
  action:
    service: tts.google_say
    data:
      entity_id: media_player.living_room_home
      message: "Welcome home, Erica"

- alias: Nobody home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: script.bedtime

- alias: Somebody is home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.living_room_light
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_light