- alias: Nobody home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: script.bedtime

- alias: Somebody is home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.living_room_light
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_light
    - service: switch.turn_on
      data:
        entity_id: switch.bedroom_light

- alias: Goal horn button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: single
  action:
    service: script.goal_horn

- alias: Bedroom lights button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016dbf86
      click_type: single
  action:
    service: switch.toggle
    data:
      entity_id: switch.bedroom_light

- alias: Bedtime button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016dbf86
      click_type: double
  action:
    service: script.bedtime

- alias: Devils Gametime
  trigger:
    platform: state
    entity_id: calendar.devils_games
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: script.google_home_sound
    data_template:
      file: "hells_bells.mp3"