- alias: Jim is Home
  trigger:
    platform: state
    entity_id: device_tracker.jim_cell
    from: 'not_home'
    to: 'home'
  action:
    service: tts.google_say
    data:
      entity_id: media_player.living_room_home
      message: "Welcome home, Jim"