homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 32
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - netgear_router
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

notify:
  - name: jim_pushbullet
    platform: pushbullet
    api_key: !secret jim_pushbullet_token
  - name: erica_pushbullet
    platform: pushbullet
    api_key: !secret erica_pushbullet_token

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: False
  - platform: asuswrt
    host: 10.0.0.1
    username: !secret router_user
    password: !secret router_password
    protocol: ssh
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

tts:
  platform: google

sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - alerts
      - feelslike_f
      - precip_today_string
      - temp_high_1d_f
      - temp_low_1d_f
      - weather
  - platform: nhl_box_score
    team: 'New Jersey Devils'
    calendar: 'calendar.new_jersey_devils'
  - platform: mqtt
    state_topic: 'assistant/+/intent'
    name: 'Assistant Command Sensor'
    qos: 2

switch 2:
  - platform: broadlink
    host: 10.0.0.4
    mac: !secret broadlink1_mac

switch 3:
  - platform: broadlink
    host: 10.0.0.11
    mac: !secret broadlink2_mac

python_script:

logger:
  default: warning
  logs:
    homeassistant.components.switch.broadlink: info
    homeassistant.components.python_script: info
    homeassistant.components.recorder: info
    homeassistant.components.media_player.plex: critical

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sun:

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi1_mac
      key: !secret xiaomi1_key

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include groups.yaml
script: !include script.yaml
switch: !include switch.yaml
automation: !include automations.yaml
zone: !include zones.yaml
input_boolean: !include input_boolean.yaml
light: !include light.yaml

##############################################################
#                       ENABLED                              #
##############################################################

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.pws_feelslike_f
      - sensor.pws_precip_today_string
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_weather
      - binary_sensor.motion_sensor_158d0001661247
    domains:
      - sun
      - media_player
      - group
      - device_tracker

# Enables the frontend
frontend:

# Enables configuration UI
config:

recorder:
  purge_interval: 2
  purge_keep_days: 2

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
