homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 32
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - netgear_router
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

device_tracker:
  - platform: owntracks
    track_new_devices: False
  - platform: bluetooth_tracker
    track_new_devices: False
  - platform: asuswrt
    host: 10.0.0.1
    username: !secret router_user
    password: !secret router_password
    protocol: ssh

tts:
  platform: google

sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - alerts
      - feelslike_f
      - precip_today_string
      - temp_high_1d_f
      - temp_low_1d_f
      - weather
  - platform: nhl_box_score
    team: 'New Jersey Devils'
    calendar: 'calendar.devils_games'

switch 2:
  - platform: broadlink
    host: 10.0.0.4
    mac: !secret broadlink1_mac

switch 3:
  - platform: broadlink
    host: 10.0.0.11
    mac: !secret broadlink2_mac

shell_command:
  intent_processor: "/srv/homeassistant/bin/python3 /home/homeassistant/.homeassistant/python_scripts/intent_processor.py {{ topic }} '{{ intent }}'"

python_script:

logger:
  default: warning
  logs:
    homeassistant.components.switch.broadlink: info
    homeassistant.components.python_script: info
    homeassistant.components.recorder: info
    homeassistant.components.media_player.plex: critical

emulated_hue:
  type: google_home
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - media_player
    - script

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sun:

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi1_mac
      key: !secret xiaomi1_key

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include groups.yaml
script: !include script.yaml
switch: !include switch.yaml
automation: !include automations.yaml
zone: !include zones.yaml
input_boolean: !include input_boolean.yaml
light: !include light.yaml

##############################################################
#                       ENABLED                              #
##############################################################

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.pws_feelslike_f
      - sensor.pws_precip_today_string
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_weather
      - device_tracker.bt_erica_cell
      - device_tracker.bt_jim_cell
      - binary_sensor.motion_sensor_158d0001661247
    domains:
      - sun
      - media_player
      - group

# Enables the frontend
frontend:

# Enables configuration UI
config:

recorder:
  purge_days: 2

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
