homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

device_tracker:
  - platform: owntracks
  - platform: bluetooth_tracker
    track_new_devices: False

tts:
  platform: google

sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - alerts
      - feelslike_f
      - precip_today_string
      - temp_high_1d_f
      - temp_low_1d_f
      - weather  

switch 2:
  - platform: broadlink
    host: 10.0.0.4
    mac: !secret broadlink1_mac

switch 3:
  - platform: broadlink
    host: 10.0.0.11
    mac: !secret broadlink2_mac

python_script:

logger:
  default: warning
  logs:
    homeassistant.components.switch.broadlink: info
    homeassistant.components.python_script: info

emulated_hue:
  type: google_home
  listen_port: 80
  exposed_domains:
    - switch
    - media_player
    - script

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include groups.yaml
script: !include script.yaml
switch: !include switch.yaml
automation: !include automations.yaml
zone: !include zones.yaml
input_boolean: !include input_boolean.yaml

##############################################################
#                       ENABLED                              #
##############################################################

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123