version: '3'
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - $HOME/hass/mariadb:/config
    env_file:
      - $HOME/hass/mariadb/mariadb.env
    ports:
      - 3306:3306

  mosquitto:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - $HOME/hass/syncthing/data/mosquitto_config:/mosquitto/config
      - $HOME/hass/mosquitto/data:/mosquitto/data
      - $HOME/hass/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
      - "9001:9001"

  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2024.5.1
    restart: unless-stopped
    privileged: true
    volumes:
      - $HOME/hass/HASSConfiguration/hass:/config
      - $HOME/hass/syncthing/data/hass_secrets/secrets_hass.yaml:/config/secrets.yaml
      - $HOME/hass/syncthing/data/hass_www:/config/www
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    depends_on:
      - "mosquitto"
      - "mariadb"
      - "syncthing"
      - "dockermon"

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:4.4.2
    restart: unless-stopped
    privileged: true
    volumes:
      - $HOME/hass/HASSConfiguration/appdaemon:/conf
      - $HOME/hass/syncthing/data/hass_secrets/secrets_appdaemon.yaml:/conf/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
      - $HOME/hass/HASSConfiguration/entity_map.yaml:/conf/apps/util/entity_map.yaml
    expose:
      - "5000"
    ports:
      - 5050:5050
    depends_on:
      - "homeassistant"

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:9.12.0
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - $HOME/hass/zwavejs/store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.37.0
    volumes:
      - $HOME/hass/zig2mqtt:/app/data
    restart: unless-stopped
    network_mode: host
    devices:
      - '/dev/zigbee:/dev/ttyUSB2'
    environment:
      - TZ=America/New_York

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - $HOME/hass/syncthing/config:/config
      - $HOME/hass/syncthing/data:/data
      - $HOME/hass/HASSConfiguration:/hass
      - $HOME/hass/zwavejs:/zwavejs
      - $HOME/hass/zig2mqtt:/zig2mqtt
    network_mode: host
    restart: unless-stopped

  dockermon:
    container_name: dockermon
    image: philhawthorne/ha-dockermon
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8126:8126

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  amcrest2mqtt:
    container_name: amcrest2mqtt
    image: dchesterton/amcrest2mqtt:latest
    restart: unless-stopped
    environment:
      AMCREST_HOST: 10.0.0.51
      AMCREST_PASSWORD: Anycolor92!
      MQTT_HOST: 10.0.0.6
      MQTT_USERNAME: amcrest
      MQTT_PASSWORD: amcrestpass
      MQTT_QOS: 2
      HOME_ASSISTANT: "false"

volumes:
  portainer-data:
