version: '3'
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - /home/dietpi/mariadb:/config
    env_file:
      - /home/dietpi/mariadb.env
    ports:
      - 3306:3306

  mosquitto:
    container_name: mqtt-broker
    image: eclipse-mosquitto:1.6.15
    restart: unless-stopped
    volumes:
      - /home/dietpi/syncthing/data/mosquitto_config:/mosquitto/config
      - /home/dietpi/mosquitto/data:/mosquitto/data
      - /home/dietpi/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
      - "9001:9001"

  homeassistant:
    container_name: home-assistant
    image: homeassistant/tinker-homeassistant:2023.4.6
    restart: unless-stopped
    privileged: true
    volumes:
      - /home/dietpi/HASSConfiguration/hass:/config
      - /home/dietpi/syncthing/data/hass_secrets/secrets_hass.yaml:/config/secrets.yaml
      - /home/dietpi/syncthing/data/hass_www:/config/www
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    depends_on:
      - "mosquitto"
      - "mariadb"
      - "syncthing"
      - "dockermon"

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:4.4.2
    restart: unless-stopped
    privileged: true
    volumes:
      - /home/dietpi/HASSConfiguration/appdaemon:/conf
      - /home/dietpi/syncthing/data/hass_secrets/secrets_appdaemon.yaml:/conf/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/dietpi/HASSConfiguration/entity_map.yaml:/conf/apps/util/entity_map.yaml
    expose:
      - "5000"
    ports:
      - 5050:5050
    depends_on:
      - "homeassistant"

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:8.14.1
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    devices:
      - '/dev/zwave:/dev/ttyUSB0'
    volumes:
      - /home/dietpi/zwavejs/store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.30.3
    volumes:
      - /home/dietpi/zig2mqtt:/app/data
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - '/dev/zigbee:/dev/ttyUSB0'
    environment:
      - TZ=America/New_York

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:arm32v7-latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - /home/dietpi/syncthing/config:/config
      - /home/dietpi/syncthing/data:/data
      - /home/dietpi/HASSConfiguration:/hass
      - /home/dietpi/zwavejs:/zwavejs
      - /home/dietpi/zig2mqtt:/zig2mqtt
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  dockermon:
    container_name: dockermon
    image: philhawthorne/ha-dockermon:arm
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8126:8126
