version: '3'
services:
  mariadb:
    container_name: mariadb
    image: lsioarmhf/mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /home/dietpi/mariadb:/config
    environment:
      TZ: "America/New_York"
  mosquitto:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - /home/dietpi/mosquitto/config:/mosquitto/config
      - /home/dietpi/mosquitto/data:/mosquitto/data
      - /home/dietpi/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
      - "9001:9001"
  smartthingsbridge:
    container_name: smartthings-bridge
    image: t0rx/rpi-smartthings-mqtt-bridge
    restart: unless-stopped
    volumes:
      - /home/dietpi/smartthingsmqttbridge:/config
    ports:
      - "8080:8080"
    depends_on:
      - "mosquitto"
  homeassistant:
    container_name: home-assistant
    image: homeassistant/tinker-homeassistant:0.91.3
    restart: unless-stopped
    volumes:
      - /home/dietpi/HASSConfiguration/hass:/config
      - /home/dietpi/secrets_hass.yaml:/config/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    network_mode: host
    depends_on:
      - "mosquitto"
      - "mariadb"
  appdaemon:
    container_name: appdaemon
    build: /home/dietpi/appdaemon
    restart: unless-stopped
    volumes:
      - /home/dietpi/HASSConfiguration/appdaemon:/conf
      - /home/dietpi/secrets_appdaemon.yaml:/conf/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "5000"
    depends_on:
      - "homeassistant"
    
    