version: '3'
services:
  mariadb:
    container_name: mariadb
    image: yobasystems/alpine-mariadb:armhf
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /home/dietpi/mariadb:/var/lib/mysql
    env_file:
      - /home/dietpi/mariadb.env
  mosquitto:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - /home/dietpi/mosquitto/config:/mosquitto/config
      - /home/dietpi/mosquitto/data:/mosquitto/data
      - /home/dietpi/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
      - "9001:9001"
  homeassistant:
    container_name: home-assistant
    image: homeassistant/tinker-homeassistant:0.110.3
    restart: unless-stopped
    volumes:
      - /home/dietpi/HASSConfiguration/hass:/config
      - /home/dietpi/secrets_hass.yaml:/config/secrets.yaml
      - /home/dietpi/jim.jpg:/config/www/jim.jpg
      - /home/dietpi/erica.jpg:/config/www/erica.jpg
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    network_mode: host
    depends_on:
      - "mosquitto"
      - "mariadb"
  appdaemon:
    container_name: appdaemon
    build: /home/dietpi/appdaemon
    restart: unless-stopped
    volumes:
      - /home/dietpi/HASSConfiguration/appdaemon:/conf
      - /home/dietpi/secrets_appdaemon.yaml:/conf/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
      - ./entity_map.yaml:/conf/apps/util/entity_map.yaml
    expose:
      - "5000"
    depends_on:
      - "homeassistant"
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:arm32v7-latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - /home/dietpi/syncthing/config:/config
      - /home/dietpi/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:master
  #   restart: unless-stopped
  #   volumes:
  #     - /home/dietpi/grafana:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - "homeassistant"
    
    