- platform: rpi_rf
  gpio: 21
  switches:
    lamps:
      code_on: !secret lamps_on_rf
      code_off: !secret lamps_off_rf
      pulselength: 184
- platform: command_line
  switches:
    bedroom_light:
      friendly_name: 'Bedroom Light'
      command_on: !secret switchmate1_on
      command_off: !secret switchmate1_off
    living_room_light:
      friendly_name: 'Living Room Light'
      command_on: !secret switchmate2_on
      command_off: !secret switchmate2_off
    kitchen_light:
      friendly_name: 'Kitchen Light'
      command_on: !secret switchmate3_on
      command_off: !secret switchmate3_off