- platform: template
  switches:
    bedroom_light:
      friendly_name: 'Bedroom Light'
      value_template: "{{ is_state('input_boolean.bedroom_switchmate', 'on') }}"
      turn_on:
        event: bedroom_switchmate
        event_data:
          command: switch
          on: True
      turn_off:
        event: bedroom_switchmate
        event_data:
          command: switch
          on: False
    living_room_light:
      friendly_name: 'Living Room Light'
      value_template: "{{ is_state('input_boolean.living_room_switchmate', 'on') }}"
      turn_on:
        event: living_room_switchmate
        event_data:
          command: switch
          on: True
      turn_off:
        event: living_room_switchmate
        event_data:
          command: switch
          on: False
    kitchen_light:
      friendly_name: 'Kitchen Light'
      value_template: "{{ is_state('input_boolean.kitchen_switchmate', 'on') }}"
      turn_on:
        event: kitchen_switchmate
        event_data:
          command: switch
          on: True
      turn_off:
        event: kitchen_switchmate
        event_data:
          command: switch
          on: False
- platform: template
  switches:
    living_room_tv:
      friendly_name: "Living Room TV"
      value_template: "{{ is_state('input_boolean.living_room_tv', 'on') }}"
      turn_on:
        service: script.living_room_tv_on
      turn_off:
        service: script.living_room_tv_off
    bedroom_tv:
      friendly_name: "Bedroom TV"
      value_template: "{{ is_state('input_boolean.bedroom_tv', 'on') }}"
      turn_on:
        service: script.bedroom_tv_on
      turn_off:
        service: script.bedroom_tv_off
