- platform: universal
  name: Living Room TV
  children:
    - media_player.living_room_speaker
    - media_player.living_room_shield
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.vizio_smartcast
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.vizio_smartcast
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.vizio_smartcast
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.vizio_smartcast
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id: media_player.vizio_smartcast
        is_volume_muted: '{{ is_volume_muted }}'
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.vizio_smartcast
        source: '{{ source }}'
  attributes:
    state: media_player.vizio_smartcast
    is_volume_muted: media_player.vizio_smartcast|is_volume_muted
    volume_level: media_player.vizio_smartcast|volume_level
    source: media_player.vizio_smartcast|source
    source_list: media_player.vizio_smartcast|source_list

- platform: universal
  name: Master Bedroom TV
  children:
    - media_player.viziocastdisplay1515
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.master_tv
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.master_tv
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.master_tv
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.master_tv
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id: media_player.master_tv
        is_volume_muted: '{{ is_volume_muted }}'
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.master_tv
        source: '{{ source }}'
  attributes:
    state: media_player.master_tv
    is_volume_muted: media_player.master_tv|is_volume_muted
    volume_level: media_player.master_tv|volume_level
    source: media_player.master_tv|source
    source_list: media_player.master_tv|source_list
    
- platform: universal
  name: Basement TV
  children:
    - media_player.basement_mibox
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.basement_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.basement_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_mute
  attributes:
    state: input_boolean.basement_tv
    
- platform: universal
  name: Guest Bedroom TV
  children:
    - media_player.guest_bedroom_mibox
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.guest_bedroom_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.guest_bedroom_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_mute
  attributes:
    state: input_boolean.guest_bedroom_tv