- platform: universal
  unique_id: universal.living_room_tv
  name: Living Room TV
  children:
    - media_player.living_room_speaker
    - media_player.living_room_shield
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.living_room_vizio_tv
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.living_room_vizio_tv
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.living_room_vizio_tv
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.living_room_vizio_tv
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id: media_player.living_room_vizio_tv
        is_volume_muted: '{{ is_volume_muted }}'
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.living_room_vizio_tv
        source: '{{ source }}'
  attributes:
    state: media_player.living_room_vizio_tv
    is_volume_muted: media_player.living_room_vizio_tv|is_volume_muted
    volume_level: media_player.living_room_vizio_tv|volume_level
    source: media_player.living_room_vizio_tv|source
    source_list: media_player.living_room_vizio_tv|source_list

- platform: universal
  unique_id: universal.master_bedroom_tv
  name: Master Bedroom TV
  children:
    - media_player.master_bedroom_tcl
    - media_player.master_bedroom_gtv
  commands:
    turn_on:
      service: remote.turn_on
      data:
        entity_id: remote.master_bedroom_tcl
    turn_off:
      service: remote.turn_off
      data:
        entity_id: remote.master_bedroom_tcl
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.master_bedroom_tcl
        command: volume_up
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.master_bedroom_tcl
        command: volume_down
    volume_mute:
      service: remote.send_command
      data_template:
        entity_id: remote.master_bedroom_tcl
        command: volume_mute
        is_volume_muted: '{{ is_volume_muted }}'
    select_source:
      service: remote.send_command
      data_template:
        entity_id: remote.master_bedroom_tcl
        command: input_hdmi4
        source: '{{ source }}'
  attributes:
    state: remote.master_bedroom_tcl
    is_volume_muted: media_player.master_bedroom_tcl|is_volume_muted
    volume_level: media_player.master_bedroom_tcl|volume_level
    source: media_player.master_bedroom_tcl|source
    source_list: media_player.master_bedroom_tcl|source_list
    
- platform: universal
  unique_id: universal.basement_tv
  name: Basement TV
  children:
    - media_player.basement_gtv
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.basement_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.basement_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_mute
  attributes:
    state: input_boolean.basement_tv
    
- platform: universal
  unique_id: universal.guest_bedroom_tv
  name: Guest Bedroom TV
  children:
    - media_player.guest_bedroom_gtv
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.guest_bedroom_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.guest_bedroom_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_mute
  attributes:
    state: input_boolean.guest_bedroom_tv