- platform: universal
  name: Living Room TV
  children:
    - media_player.shield
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.vizio_smartcast
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.vizio_smartcast
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.vizio_smartcast
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.vizio_smartcast
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.vizio_smartcast
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.vizio_smartcast
        source: '{{ source }}'
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.vizio_smartcast
        volume_level: '{{ volume_level }}'
  attributes:
    state: media_player.vizio_smartcast
    is_volume_muted: media_player.vizio_smartcast|is_volume_muted
    volume_level: media_player.vizio_smartcast|volume_level
    source: media_player.vizio_smartcast|source
    source_list: media_player.vizio_smartcast|source_list

- platform: universal
  name: Master Bedroom TV
  children:
    - media_player.mibox3
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.master_bedroom_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.master_bedroom_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.master_bedroom_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.master_bedroom_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.master_bedroom_tv_mute
  attributes:
    state: input_boolean.master_bedroom_tv