- platform: generic_thermostat
  name: Fourth Bedroom AC
  heater: switch.fourth_bedroom_ac
  target_sensor: sensor.temperature_158d00023cf950
  ac_mode: true
  min_cycle_duration:
    seconds: 5
  initial_operation_mode: "off"