- platform: generic_thermostat
  name: Fourth Bedroom AC
  heater: switch.fourth_bedroom_ac
  target_sensor: sensor.lumi_lumi_weather_023cf950_1_1026
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Master Bedroom AC
  heater: switch.master_bedroom_ac
  target_sensor: sensor.lumi_lumi_weather_0245a6a2_1_1026
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  keep_alive:
    minutes: 2
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Dining Room AC
  heater: switch.dining_room_ac
  target_sensor: sensor.lumi_lumi_weather_01d6f386_1_1026
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Guest Bedroom AC
  heater: switch.guest_bedroom_ac
  target_sensor: sensor.lumi_lumi_weather_023cf8f7_1_1026
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  keep_alive:
    minutes: 2
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Office AC
  heater: switch.office_ac
  target_sensor: sensor.lumi_lumi_weather_0245ae4b_1_1026
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  keep_alive:
    minutes: 2
  initial_hvac_mode: "off"
  precision: 0.1