- platform: generic_thermostat
  name: Fourth Bedroom AC
  heater: switch.fourth_bedroom_ac
  target_sensor: sensor.temperature_158d00023cf950
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  precision: 1.0

- platform: generic_thermostat
  name: Dining Room AC
  heater: switch.dining_room_ac
  target_sensor: sensor.temperature_158d0001d6f386
  ac_mode: true
  min_temp: 65
  max_temp: 80
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    seconds: 30
  precision: 1.0

- platform: smartir
  name: Office Minisplit
  unique_id: office_minisplit
  device_code: 2040
  controller_data: remote.office_broadlink_remote
  temperature_sensor: sensor.temperature_158d000245ae4b

- platform: smartir
  name: Master Bedroom Minisplit
  unique_id: master_bedroom_minisplit
  device_code: 2040
  controller_data: remote.master_bedroom_broadlink_remote
  temperature_sensor: sensor.temperature_158d000245a6a2

- platform: smartir
  name: Guest Bedroom Minisplit
  unique_id: guest_bedroom_minisplit
  device_code: 2040
  controller_data: remote.guest_bedroom_broadlink_remote
  temperature_sensor: sensor.temperature_158d00023cf8f7