homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone

lovelace:
  mode: storage
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true

mqtt:
  sensor:
    - name: "Backyard Temperature"
      state_topic: "rtl_433/+/devices/Acurite-Tower/A/3658/temperature_C"
      unit_of_measurement: "°F"
      device_class: temperature
      value_template: "{{(float(value_json) * 9/5)+32}}"
    - name: "Pool Temperature"
      state_topic: "rtl_433/+/devices/Inkbird-ITH20R/14856/temperature_C"
      unit_of_measurement: "°F"
      device_class: temperature
      value_template: "{{(float(value_json) * 9/5)+32}}"
    - name: "iGrill Probe 1"
      state_topic: "temperature/grill/grill/probe1"
      unit_of_measurement: "°F"
      device_class: temperature
    - name: "iGrill Probe 2"
      state_topic: "temperature/grill/grill/probe2"
      unit_of_measurement: "°F"
      device_class: temperature
    - name: "iGrill Probe 3"
      state_topic: "temperature/grill/grill/probe3"
      unit_of_measurement: "°F"
      device_class: temperature
    - name: "iGrill Probe 4"
      state_topic: "temperature/grill/grill/probe4"
      unit_of_measurement: "°F"
      device_class: temperature
    - name: "iGrill Battery"
      state_topic: "temperature/grill/grill/battery"
      unit_of_measurement: "%"
      device_class: battery

notify:
  - platform: joaoapps_join
    api_key: !secret jim_join_key
    device_names: jim_cell
    name: jim_cell
  - platform: joaoapps_join
    api_key: !secret erica_join_key
    device_names: erica_cell
    name: erica_cell
joaoapps_join:
  - name: jim_cell
    device_id: !secret jim_cell_device_id
    api_key: !secret jim_join_key
  - name: erica_cell
    device_id: !secret erica_cell_device_id
    api_key: !secret erica_join_key

owntracks:
  secret: !secret owntracks_encryption
  waypoints: false
  
smartir:
  check_updates: false

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
zone: !include zones.yaml
input_boolean: !include input/input_boolean.yaml
input_number: !include input/input_number.yaml
light: !include_dir_merge_list light/
panel_iframe: !include_dir_merge_named panel_iframes/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
media_player: !include_dir_merge_list media_player/
input_select: !include input/input_select.yaml
yeelight: !include_dir_merge_named yeelight/
climate: !include climate.yaml
binary_sensor: !include_dir_merge_list binary_sensor/
cover: !include_dir_merge_list cover/
rest_command: !include rest_command.yaml
scene: !include scenes.yaml

##############################################################
#                       ENABLED                              #
##############################################################
config:
map:
system_health:
mobile_app:
sun:
media_source:
tag:
my:

logger:
  default: error

# View all events in a logbook
logbook: !include logbook.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 10
  exclude:
    domains:
      - zwave
    entities:
      - sensor.hank_hkzw_so03_smart_plug_voltage_2
      - sensor.hank_hkzw_so03_smart_plug_voltage
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_4
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_3
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_2
      - sensor.hank_hkzw_so03_smart_plug_previous_reading
      - sensor.hank_hkzw_so03_smart_plug_power_2
      - sensor.hank_hkzw_so03_smart_plug_power
      - sensor.hank_hkzw_so03_smart_plug_energy_2
      - sensor.hank_hkzw_so03_smart_plug_energy
      - sensor.hank_hkzw_so03_smart_plug_current_2
      - sensor.hank_hkzw_so03_smart_plug_current

history:
  exclude:
    domains:
      - zwave
    entities:
      - sensor.hank_hkzw_so03_smart_plug_voltage_2
      - sensor.hank_hkzw_so03_smart_plug_voltage
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_4
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_3
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_2
      - sensor.hank_hkzw_so03_smart_plug_previous_reading
      - sensor.hank_hkzw_so03_smart_plug_power_2
      - sensor.hank_hkzw_so03_smart_plug_power
      - sensor.hank_hkzw_so03_smart_plug_energy_2
      - sensor.hank_hkzw_so03_smart_plug_energy
      - sensor.hank_hkzw_so03_smart_plug_current_2
      - sensor.hank_hkzw_so03_smart_plug_current