homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 54
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - netgear_router
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

notify:
  - name: jim_pushbullet
    platform: pushbullet
    api_key: !secret jim_pushbullet_token
  - name: erica_pushbullet
    platform: pushbullet
    api_key: !secret erica_pushbullet_token

device_tracker:
  - platform: owntracks
    secret: !secret owntracks_encryption
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  # - platform: asuswrt
  #   host: 10.0.0.1
  #   username: !secret router_user
  #   password: !secret router_password
  #   protocol: ssh
  #   mode: ap
  #   new_device_defaults:
  #     track_new_devices: False
  #     hide_if_away: False

tts:
  platform: google

cast:

binary_sensor:
  - platform: ping
    name: Google DNS Ping
    host: 8.8.8.8
    count: 5
    scan_interval: 300

media_player:
  - platform: vizio
    host: 10.0.0.5
    scan_interval: 30
    access_token: !secret living_room_vizio_token

sensor:
  - platform: darksky
    api_key: !secret dark_sky_key
    update_interval:
      minutes: 30
    monitored_conditions:
      - temperature
      - humidity
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon

  - platform: nhl_box_score
    team: 'New Jersey Devils'
    calendar: 'calendar.new_jersey_devils'
  
logger:
  default: warning
  logs:
    homeassistant.components.switch.broadlink: info
    homeassistant.components.recorder: info
    homeassistant.components.media_player.plex: critical

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sun:

vacuum:
  - platform: xiaomi_miio
    host: 10.0.0.19
    token: !secret xiaomi_vacuum_key

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi1_mac
      key: !secret xiaomi1_key

zwave:
  usb_path: /dev/ttyUSB0

zha_new:
    usb_path: /dev/ttyUSB1
    database_path: /home/homeassistant/.homeassistant/zigbee.db

# zha:
#   usb_path: /dev/ttyUSB1
#   database_path: /home/homeassistant/.homeassistant/zigbee.db

august:
  login_method: email
  username: !secret august_user
  password: !secret august_pass

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
switch: !include switch.yaml
automation: !include_dir_merge_list automations/
zone: !include zones.yaml
input_boolean: !include input_boolean.yaml
light: !include light.yaml
shell_command: !include_dir_merge_named shell_commands/
panel_iframe: !include_dir_merge_named panel_iframes/

##############################################################
#                       ENABLED                              #
##############################################################

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.pws_feelslike_f
      - sensor.pws_precip_today_string
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_weather
      - binary_sensor.motion_sensor_158d0001661247
      - automation.generate_zwave_graph
    domains:
      - sun
      - media_player
      - group
      - device_tracker

# Enables the frontend
frontend:
  themes:
    darkorange:
      primary-color: "#ff9800"
      light-primary-color: "#ffc947"
      dark-primary-color: "#c66900"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#62717b"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--sidebar-text_-_background)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

# Enables configuration UI
config:

map:

recorder:
  db_url: !secret mariadb_url
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.hank_hkzwso03_smart_plug_voltage_2
      - sensor.hank_hkzwso03_smart_plug_voltage
      - sensor.hank_hkzwso03_smart_plug_previous_reading_4
      - sensor.hank_hkzwso03_smart_plug_previous_reading_3
      - sensor.hank_hkzwso03_smart_plug_previous_reading_2
      - sensor.hank_hkzwso03_smart_plug_previous_reading
      - sensor.hank_hkzwso03_smart_plug_power_2
      - sensor.hank_hkzwso03_smart_plug_power
      - sensor.hank_hkzwso03_smart_plug_energy_2
      - sensor.hank_hkzwso03_smart_plug_energy
      - sensor.hank_hkzwso03_smart_plug_current_2
      - sensor.hank_hkzwso03_smart_plug_current

history:
  exclude:
    entities:
      - sensor.hank_hkzwso03_smart_plug_voltage_2
      - sensor.hank_hkzwso03_smart_plug_voltage
      - sensor.hank_hkzwso03_smart_plug_previous_reading_4
      - sensor.hank_hkzwso03_smart_plug_previous_reading_3
      - sensor.hank_hkzwso03_smart_plug_previous_reading_2
      - sensor.hank_hkzwso03_smart_plug_previous_reading
      - sensor.hank_hkzwso03_smart_plug_power_2
      - sensor.hank_hkzwso03_smart_plug_power
      - sensor.hank_hkzwso03_smart_plug_energy_2
      - sensor.hank_hkzwso03_smart_plug_energy
      - sensor.hank_hkzwso03_smart_plug_current_2
      - sensor.hank_hkzwso03_smart_plug_current

http:
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1