homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 54
  unit_system: imperial
  time_zone: !secret home_timezone

lovelace:
  mode: yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user

notify:
  - platform: joaoapps_join
    api_key: !secret jim_join_key
    device_names: jim_cell
    name: jim_cell
joaoapps_join:
  - name: jim_cell
    device_id: !secret jim_cell_device_id
    api_key: !secret jim_join_key

tts:
  platform: google

cast:
  media_player:
    - host: 10.0.0.26 # living room tv
    - host: 10.0.0.33 # living room speaker
    - host: 10.0.0.27 # backyard speaker
    - host: 10.0.0.28 # master bedroom tv
    - host: 10.0.0.29 # basement tv

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sun:

vacuum:
  - platform: xiaomi_miio
    host: 10.0.0.19
    token: !secret xiaomi_vacuum_key

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi1_mac
      key: !secret xiaomi1_key

zwave:
  usb_path: /dev/ttyUSB0

# zha_new:
#     usb_path: /dev/ttyUSB1
#     database_path: /home/homeassistant/.homeassistant/zigbee_new.db

# zha:
#   usb_path: /dev/ttyUSB1
#   database_path: /home/homeassistant/.homeassistant/zigbee.db

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

owntracks:
  secret: !secret owntracks_encryption

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
zone: !include zones.yaml
input_boolean: !include input_boolean.yaml
light: !include_dir_merge_list light/
shell_command: !include_dir_merge_named shell_commands/
panel_iframe: !include_dir_merge_named panel_iframes/
binary_sensor: !include_dir_merge_list binary_sensor/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
device_tracker: !include_dir_merge_list device_tracker/
media_player: !include_dir_merge_list media_player/
input_select: !include_dir_merge_named input_select/

##############################################################
#                       ENABLED                              #
##############################################################

logger:
  default: error

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.pws_feelslike_f
      - sensor.pws_precip_today_string
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_weather
      - automation.generate_zwave_graph
    domains:
      - sun
      - media_player
      - group
      - device_tracker

# Enables the frontend
frontend:
  themes:
    darkorange:
      primary-color: "#ff9800"
      light-primary-color: "#ffc947"
      dark-primary-color: "#c66900"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#62717b"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--sidebar-text_-_background)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

# Enables configuration UI
config:

map:

recorder:
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    domains:
      - zwave
    entities:
      - sensor.hank_hkzwso03_smart_plug_voltage_2
      - sensor.hank_hkzwso03_smart_plug_voltage
      - sensor.hank_hkzwso03_smart_plug_previous_reading_4
      - sensor.hank_hkzwso03_smart_plug_previous_reading_3
      - sensor.hank_hkzwso03_smart_plug_previous_reading_2
      - sensor.hank_hkzwso03_smart_plug_previous_reading
      - sensor.hank_hkzwso03_smart_plug_power_2
      - sensor.hank_hkzwso03_smart_plug_power
      - sensor.hank_hkzwso03_smart_plug_energy_2
      - sensor.hank_hkzwso03_smart_plug_energy
      - sensor.hank_hkzwso03_smart_plug_current_2
      - sensor.hank_hkzwso03_smart_plug_current

history:
  exclude:
    domains:
      - zwave
    entities:
      - sensor.hank_hkzwso03_smart_plug_voltage_2
      - sensor.hank_hkzwso03_smart_plug_voltage
      - sensor.hank_hkzwso03_smart_plug_previous_reading_4
      - sensor.hank_hkzwso03_smart_plug_previous_reading_3
      - sensor.hank_hkzwso03_smart_plug_previous_reading_2
      - sensor.hank_hkzwso03_smart_plug_previous_reading
      - sensor.hank_hkzwso03_smart_plug_power_2
      - sensor.hank_hkzwso03_smart_plug_power
      - sensor.hank_hkzwso03_smart_plug_energy_2
      - sensor.hank_hkzwso03_smart_plug_energy
      - sensor.hank_hkzwso03_smart_plug_current_2
      - sensor.hank_hkzwso03_smart_plug_current

http:
  trusted_networks:
    - 127.0.0.1