homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 54
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

lovelace:
  mode: yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user

notify:
  - platform: joaoapps_join
    api_key: !secret jim_join_key
    device_names: jim_cell
    name: jim_cell
  - platform: joaoapps_join
    api_key: !secret erica_join_key
    device_names: erica_cell
    name: erica_cell
joaoapps_join:
  - name: jim_cell
    device_id: !secret jim_cell_device_id
    api_key: !secret jim_join_key
  - name: erica_cell
    device_id: !secret erica_cell_device_id
    api_key: !secret erica_join_key

cast:
  media_player:
    - host: 10.0.0.26 # living room tv
    - host: 10.0.0.33 # living room speaker
    - host: 10.0.0.27 # backyard speaker
    - host: 10.0.0.28 # master bedroom tv
    - host: 10.0.0.29 # basement tv

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sun:

vacuum:
  - platform: xiaomi_miio
    host: 10.0.0.19
    token: !secret xiaomi_vacuum_key

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi1_mac
      key: !secret xiaomi1_key

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_key

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

owntracks:
  secret: !secret owntracks_encryption
  
weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily
  
panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
zone: !include zones.yaml
input_boolean: !include input_boolean.yaml
light: !include_dir_merge_list light/
shell_command: !include_dir_merge_named shell_commands/
panel_iframe: !include_dir_merge_named panel_iframes/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
device_tracker: !include device_tracker/trackers.yaml
media_player: !include_dir_merge_list media_player/
input_select: !include_dir_merge_named input_select/
yeelight: !include_dir_merge_named yeelight/
climate: !include climate.yaml
person: !include device_tracker/persons.yaml

##############################################################
#                       ENABLED                              #
##############################################################

system_health:

logger:
  default: error

# View all events in a logbook
logbook: !include logbook.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

map:

recorder:
  db_url: !secret mariadb_url
  purge_interval: 1
  purge_keep_days: 10
  exclude:
    domains:
      - zwave
    entities:
      - sensor.hank_hkzw_so03_smart_plug_voltage_2
      - sensor.hank_hkzw_so03_smart_plug_voltage
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_4
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_3
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_2
      - sensor.hank_hkzw_so03_smart_plug_previous_reading
      - sensor.hank_hkzw_so03_smart_plug_power_2
      - sensor.hank_hkzw_so03_smart_plug_power
      - sensor.hank_hkzw_so03_smart_plug_energy_2
      - sensor.hank_hkzw_so03_smart_plug_energy
      - sensor.hank_hkzw_so03_smart_plug_current_2
      - sensor.hank_hkzw_so03_smart_plug_current

history:
  exclude:
    domains:
      - zwave
    entities:
      - sensor.hank_hkzw_so03_smart_plug_voltage_2
      - sensor.hank_hkzw_so03_smart_plug_voltage
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_4
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_3
      - sensor.hank_hkzw_so03_smart_plug_previous_reading_2
      - sensor.hank_hkzw_so03_smart_plug_previous_reading
      - sensor.hank_hkzw_so03_smart_plug_power_2
      - sensor.hank_hkzw_so03_smart_plug_power
      - sensor.hank_hkzw_so03_smart_plug_energy_2
      - sensor.hank_hkzw_so03_smart_plug_energy
      - sensor.hank_hkzw_so03_smart_plug_current_2
      - sensor.hank_hkzw_so03_smart_plug_current