homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone

lovelace:
  mode: storage

notify:
  - platform: joaoapps_join
    api_key: !secret jim_join_key
    device_names: jim_cell
    name: jim_cell
  - platform: joaoapps_join
    api_key: !secret erica_join_key
    device_names: erica_cell
    name: erica_cell
joaoapps_join:
  - name: jim_cell
    device_id: !secret jim_cell_device_id
    api_key: !secret jim_join_key
  - name: erica_cell
    device_id: !secret erica_cell_device_id
    api_key: !secret erica_join_key

owntracks:
  secret: !secret owntracks_encryption
  waypoints: false
  
smartir:
  check_updates: false

##############################################################
#                       INCLUDES                             #
##############################################################

group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
zone: !include zones.yaml
input_boolean: !include input/input_boolean.yaml
input_number: !include input/input_number.yaml
light: !include_dir_merge_list light/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
media_player: !include_dir_merge_list media_player/
input_select: !include input/input_select.yaml
yeelight: !include_dir_merge_named yeelight/
climate: !include climate.yaml
binary_sensor: !include_dir_merge_list binary_sensor/
cover: !include_dir_merge_list cover/
rest_command: !include rest_command.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml

##############################################################
#                       ENABLED                              #
##############################################################
config:
system_health:
mobile_app:
sun:
media_source:
tag:
my:
history:
assist_pipeline:

logger:
  default: error

# View all events in a logbook
logbook: !include logbook.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 14
  exclude:
    domains:
      - zwave_js
    event_types:
      - zwave_js_value_notification