- platform: yeelight
  devices:
    10.0.0.12:
      name: Living Room Lamp 1
    10.0.0.13:
      name: Living Room Lamp 2
    10.0.0.23:
      name: Jim Nightlight
    10.0.0.24:
      name: Erica Nightlight