- platform: template
  switches:
    master_bedroom_ac:
      friendly_name: "Master Bedroom AC"
      value_template: "{{ is_state('input_boolean.master_bedroom_ac', 'on') }}"
      turn_on:
        service: script.master_bedroom_ac_on
      turn_off:
        service: script.master_bedroom_ac_off
    master_bedroom_tv:
      friendly_name: "Master Bedroom TV"
      value_template: "{{ is_state('input_boolean.master_bedroom_tv', 'on') }}"
      turn_on:
        service: script.master_bedroom_tv_on
      turn_off:
        service: script.master_bedroom_tv_off
    dining_room_ac:
      friendly_name: "Dining Room AC"
      value_template: "{{ is_state('input_boolean.dining_room_ac', 'on') }}"
      turn_on:
        service: script.dining_room_ac_on
      turn_off:
        service: script.dining_room_ac_off
- platform: broadlink
  host: 10.0.0.4
  mac: !secret broadlink1_mac
- platform: broadlink
  host: 10.0.0.11
  mac: !secret broadlink2_mac