- platform: template
  switches:
    master_bedroom_ac:
      friendly_name: "Master Bedroom AC"
      value_template: "{{ is_state('input_boolean.master_bedroom_ac', 'on') }}"
      turn_on:
        service: script.master_bedroom_ac_on
      turn_off:
        service: script.master_bedroom_ac_off
    master_bedroom_tv:
      friendly_name: "Master Bedroom TV"
      value_template: "{{ is_state('input_boolean.master_bedroom_tv', 'on') }}"
      turn_on:
        service: script.master_bedroom_tv_on
      turn_off:
        service: script.master_bedroom_tv_off
    master_bedroom_light:
      friendly_name: "Master Bedroom Light"
      value_template: "{{ is_state('input_boolean.master_bedroom_light', 'on') }}"
      turn_on:
        service: script.master_bedroom_light_on
      turn_off:
        service: script.master_bedroom_light_off
    kitchen_fixture_light:
      friendly_name: 'Kitchen Light'
      value_template: "{{ is_state('input_boolean.kitchen_switchmate', 'on') }}"
      turn_on:
        event: kitchen_switchmate
        event_data:
          command: switch
          is_on: True
      turn_off:
        event: kitchen_switchmate
        event_data:
          command: switch
          is_on: False
    hallway_light:
      friendly_name: 'Hallway Light'
      value_template: "{{ is_state('input_boolean.hallway_switchmate', 'on') }}"
      turn_on:
        event: hallway_switchmate
        event_data:
          command: switch
          is_on: True
      turn_off:
        event: hallway_switchmate
        event_data:
          command: switch
          is_on: False
- platform: broadlink
  host: 10.0.0.4
  mac: !secret broadlink1_mac
- platform: broadlink
  host: 10.0.0.11
  mac: !secret broadlink2_mac