title: Home Assistant Frontend
views:
  - title: Lights
    cards:
    - type: entities
      title: Lights
      entities:
        - type: section
          label: Front Yard
        - entity: light.driveway
          name: "Driveway Light"
        - entity: light.front_garden
          name: "Front Garden Lights"
        - light.porch_light
        - type: section
          label: First Floor
        - light.living_room_lamps
        - light.piano_led
        - entity: light.stairs_led
          name: "Staircase LED"
        - light.dining_room_light
        - light.kitchen_lights
        - entity: light.gateway_light_34ce008dcec1
          name: "Gateway Light"
        - type: section
          label: Second Floor
        - light.hallway_lights
        - light.master_bedroom_fixture
        - light.jim_night_lamp
        - light.erica_night_lamp
        - light.office_lights
        - type: section
          label: Third Floor
        - light.fourth_bedroom_fixture
        - type: section
          label: Basement
        - light.basement_staircase_light
        - type: section
          label: Back Yard
        - light.deck_light

  - title: Media
    cards:
    - type: entities
      title: TVs
      show_header_toggle: false
      entities:
        - entity: media_player.living_room_tv
        - entity: media_player.master_bedroom_tv
        - entity: media_player.basement_tv
        - entity: media_player.guest_bedroom_tv
  
    - type: entities
      title: Speakers
      show_header_toggle: false
      entities:
        - entity: media_player.backyard_speaker
        
  - title: Outlets
    cards:
    - type: entities
      title: Outlets
      entities:
        - entity: switch.tradfri_outlet_2
          name: "Kitchen Fragrance"
        - entity: switch.hank_hkzw_so03_smart_plug_switch_2
          name: "Rice Cooker"
        - entity: switch.centralite_outlet_1
          name: "Kettle"
        - entity: light.piano_plug
          name: "Piano Power"
        - entity: switch.centralite_outlet_2
          name: "Couch Outlet"
        - entity: switch.centralite_outlet_3
          name: "Hallway Outlet"
        - entity: switch.hank_hkzw_so03_smart_plug_switch
          name: "Living Room Fragrance"
          
  - title: Climate
    cards:
    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Heating"
      card:
        type: thermostat
        entity:  climate.linear_gc_tbz48_battery_powered_z_wave_thermostat_heating_1
        name: Oil Heater
      
    - type: glance
      title: Temperature
      entities:
        - entity: sensor.garage_temperature
          name: Garage
        - entity: sensor.temperature_158d0001d6f386
          name: Downstairs
        - entity: sensor.front_door_temperature
          name: Front Door
        - entity: sensor.temperature_158d000245a6a2
          name: Master BR
        - entity: sensor.temperature_158d000245ae4b
          name: Office
        - entity: sensor.temperature_158d00023cf8f7
          name: Guest BR
        - entity: sensor.temperature_158d00023cf950
          name: Upstairs

  - title: Misc
    cards:
    - type: entities
      title: Lock
      show_header_toggle: false
      entities:
        - entity:  lock.assa_abloy_yale_push_button_deadbolt_yrd110_locked_2
          name: Front Door Lock

    - type: entities
      title: Garage
      show_header_toggle: false
      entities:
        - entity: switch.fortrezz_mimolite_switch
          name: Garage Door Switch
        - entity: binary_sensor.garage_sensor
          name: Garage Door Sensor

    - type: entities
      title: Vacuums
      show_header_toggle: false
      entities:
        - entity: vacuum.xiaomi_vacuum_cleaner
        
    - type: entity-filter
      entities:
        - entity: group.jim_cell_device
          icon: /local/jim.jpg
        - entity: group.erica_cell_device
          icon: /local/erica.jpg
      state_filter:
        - home
      card:
        type: glance
        title: At Home
        show_state: false

    - type: entity-button
      entity: script.generate_grocery_list
      name: Generate Mealplan
      tap_action: call_service
      service: script.turn_on
    
    - type: entity-button
      entity: script.archive_mealplan
      name: Archive Mealplan
      tap_action: call_service
      service: script.turn_on
        
  - title: Config
    cards:
    - type: entities
      title: Configuration
      show_header_toggle: false
      entities:
        - input_select.thermostat_mode
        - entity: input_boolean.sleep_mode
          name: Sleep Mode
          icon: mdi:sleep
        
  - title: Advanced
    cards:
    - type: entities
      title: Software Update
      show_header_toggle: false
      entities:
        - type: call-service
          name: Update HASS
          service: shell_command.update_hass_config
        - type: call-service
          name: Update Appdaemon
          service: shell_command.update_appdaemon_config
          
    - type: entities
      title: IR Learning
      show_header_toggle: false
      entities:
        - type: call-service
          name: Living Room Learn
          service: switch.broadlink_learn_command_10_0_0_11
        - type: call-service
          name: Master BR Learn
          service: switch.broadlink_learn_command_10_0_0_4
          
    - type: entities
      title: Zigbee Setup
      show_header_toggle: false
      entities:
        - type: call-service
          name: Add Xiaomi Device
          service: xiaomi_aqara.add_device
          service_data:
            gw_mac: !secret xiaomi1_mac
        - entity: switch.zigbee_debug
          name: Zigbee Debug Logging