title: Stys Home Control
views:
  - title: Lights
    icon: mdi:home
    cards:
      - type: glance
        title: Living Room
        entities:
          - entity:  lock.assa_abloy_yale_push_button_deadbolt_yrd110_locked_2
            name: Lock
            tap_action:
              action: toggle
          - entity: media_player.living_room_tv
            name: TV
            tap_action:
              action: toggle
          - entity: light.living_room_lamps
            name: Lamps
            tap_action:
              action: toggle
          - entity: light.piano_led
            name: PianoLED
            tap_action:
              action: toggle
          - entity: light.ledvance_flex_rgbw_000089d8_1
            name: Stairs
            tap_action:
              action: toggle
          - entity: light.dining_room_light
            name: Dining
            tap_action:
              action: toggle
          - entity: switch.centralite_3210_l_0c3283a0_1
            icon: mdi:power-socket-us
            name: "Piano"
            tap_action:
              action: toggle
          - entity: switch.hank_hkzw_so03_smart_plug_switch
            icon: mdi:power-socket-us
            name: "Couch"
            tap_action:
              action: toggle
          - entity: switch.ledvance_plug_00051d4d_1
            icon: mdi:power-socket-us
            name: "Scent"
            tap_action:
              action: toggle
      - type: glance
        title: Kitchen
        entities:
          - entity: light.kitchen_lights
            name: Lights
            tap_action:
              action: toggle
          - entity: light.kitchen_cabinets_zha_group_0x0005
            name: Cabinets
            tap_action:
              action: toggle
          - entity: vacuum.xiaomi_vacuum_cleaner
            name: Vacuum
          - entity: switch.ikea_of_sweden_tradfri_control_outlet_fe28239d_1
            icon: mdi:power-socket-us
            name: "Scent"
            tap_action:
              action: toggle
          - entity: switch.hank_hkzw_so03_smart_plug_switch_2
            icon: mdi:power-socket-us
            name: "Rice"
            tap_action:
              action: toggle
          - entity: light.centralite_4257050_rzhac_0ae7df8a_1
            icon: mdi:power-socket-us
            name: "Espresso"
            tap_action:
              action: toggle
          - entity: binary_sensor.door_window_sensor_158d0001d3a024
            name: Fridge
      - type: glance
        title: Master Bedroom
        entities:
          - entity: media_player.master_bedroom_tv
            name: "TV"
            tap_action:
              action: toggle
          - entity: light.master_bedroom_fixture
            name: "Fixture"
            tap_action:
              action: toggle
          - entity: light.jim_night_lamp
            name: "Jim"
            tap_action:
              action: toggle
          - entity: light.erica_night_lamp
            name: "Erica"
            tap_action:
              action: toggle
          - entity: light.master_bedroom_closet_zha_group_0x0004
            name: Closet
            tap_action:
              action: toggle
          - entity: light.master_bedroom_mirror_led
            name: Mirror
            tap_action:
              action: toggle
      - type: glance
        title: Office
        entities:
          - entity: climate.office_ac
            name: AC
          - entity: switch.third_reality_inc_3rss007z_ffe01818_1_6
            name: Lights
            tap_action:
              action: toggle
      - type: glance
        title: Guest Bedroom
        entities:
          - entity: media_player.guest_bedroom_tv
            name: TV
            tap_action:
              action: toggle
      - type: glance
        title: Fourth Bedroom
        entities:
          - entity: light.fourth_bedroom_fixture_zha_group_0x0003
            name: Light
            tap_action:
              action: toggle
      - type: glance
        title: Basement
        entities: 
          - entity: media_player.basement_tv
            name: TV
            tap_action:
              action: toggle
          - entity: light.cree_connected_a_19_60w_equivalent_fe05fbf3_10
            name: Staircase
            tap_action:
              action: toggle
          - entity: binary_sensor.water_leak_sensor_158d00023a58df
            name: Water Sensor
          - entity: binary_sensor.washer_running
            name: Washer
          - entity: binary_sensor.dryer_running
            name: Dryer
      - type: glance
        title: Garage
        entities:
          - entity: switch.fortrezz_mimolite_switch
            name: Garage Door Switch
            tap_action:
              action: toggle
          - entity: binary_sensor.visonic_mct_340_e_0b121b78_1_1280
            name: Garage Door Sensor
          - entity: light.front_garage_light
            name: Front Light
            tap_action:
              action: toggle

  - title: Outside
    icon: mdi:weather-sunny
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: glance
        title: Backyard
        entities:
          - entity: media_player.backyard_speaker
            name: Speakers
          - entity: light.cree_connected_a_19_60w_equivalent_fe06e97f_10
            name: Deck
            tap_action:
              action: toggle
          - entity: switch.inovelli_nzw96_1_channel_outdoor_smart_plug_switch_2
            name: Outlet
            tap_action:
              action: toggle
      - type: glance
        title: Frontyard
        entities:
          - entity: light.osram_lightify_par38_on_off_dim_00a5ee30_3
            name: Driveway
            tap_action:
              action: toggle
          - entity: light.osram_lightify_gardenspot_rgb_00a72c35_3
            name: Garden
            tap_action:
              action: toggle
          - entity: light.osram_lightify_a19_on_off_dim_10_year_20eb0d00_level_on_off
            name: Porch
            tap_action:
              action: toggle
          - entity: switch.ikea_of_sweden_tradfri_control_outlet_fe33e45c_1
            name: Poutlet
            tap_action:
              action: toggle
          - entity: switch.inovelli_nzw96_1_channel_outdoor_smart_plug_switch
            name: Outlet
            tap_action:
              action: toggle
          
  - title: Climate
    icon: mdi:thermometer-lines
    cards:
    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Heating"
      card:
        type: thermostat
        entity: climate.linear_gc_tbz48_battery_powered_z_wave_thermostat_mode
        name: Oil Heater

    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Cooling"
      card:
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity:  climate.dining_room_ac
                name: Dining Room
              - type: thermostat
                entity:  climate.master_bedroom_ac
                name: Master Bedroom
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity:  climate.guest_bedroom_ac
                name: Guest Bedroom
              - type: thermostat
                entity:  climate.fourth_bedroom_ac
                name: Fourth Bedroom
      
    - type: glance
      title: Temperature
      entities:
        - entity: sensor.visonic_mct_340_e_0b121b78_1_1026
          name: Garage
        - entity: sensor.temperature_158d0001d6f386
          name: Downstairs
        - entity: sensor.visonic_mct_340_e_0b121662_1_1026
          name: Front Door
        - entity: sensor.temperature_158d000245a6a2
          name: Master BR
        - entity: sensor.temperature_158d000245ae4b
          name: Office
        - entity: sensor.temperature_158d00023cf8f7
          name: Guest BR
        - entity: sensor.temperature_158d00023cf950
          name: Upstairs

    - type: glance
      title: Humidity
      entities:
        - entity: sensor.humidity_158d0001d6f386
          name: Downstairs
        - entity: sensor.humidity_158d000245a6a2
          name: Master BR
        - entity: sensor.humidity_158d000245ae4b
          name: Office
        - entity: sensor.humidity_158d00023cf8f7
          name: Guest BR
        - entity: sensor.humidity_158d00023cf950
          name: Upstairs

  - title: Cameras
    icon: mdi:camcorder
    cards:
      - type: picture-glance
        title: Front Door
        camera_image: camera.front_door_camera
        camera_view: live
        entities:
          - binary_sensor.front_door_camera_motion_detected
          - binary_sensor.front_door_camera_online

  - title: Batteries
    icon: mdi:battery-charging
    cards:
    - type: entities
      title: Battery Levels
      show_header_toggle: false
      entities:
        - type: section
          label: Temperature
        - entity: sensor.downstairs_temperature_battery
        - entity: sensor.master_bedroom_temperature_battery
        - entity: sensor.office_temperature_battery
        - entity: sensor.guest_bedroom_temperature_battery
        - type: section
          label: Door
        - entity: sensor.fridge_door_battery
        - type: section
          label: Button
        - entity: sensor.master_bedroom_button_battery
        - type: section
          label: Motion
        - entity: sensor.hallway_motion_battery
        - entity: sensor.landing_motion_battery
        - entity: sensor.office_motion_battery
        - type: section
          label: Water
        - entity: sensor.basement_water_battery
        
  - title: Config
    icon: mdi:settings
    cards:
    - type: entities
      title: Configuration
      show_header_toggle: false
      entities:
        - input_select.thermostat_mode
        - entity: input_boolean.sleep_mode
          name: Sleep Mode
          icon: mdi:sleep
        - entity: input_boolean.guest_mode
          name: Guest Mode
          icon: mdi:home-account
        - entity: input_boolean.christmas_lights
          icon: mdi:pine-tree
        
  - title: Advanced
    icon: mdi:android-debug-bridge
    cards:
      - type: entities
        title: Meal Plan
        show_header_toggle: false
        entities:
          - entity: script.generate_grocery_list
            name: Generate Mealplan
            icon: mdi:pasta
          - entity: script.archive_mealplan
            name: Archive Mealplan
            icon: mdi:pasta

      - type: entities
        title: Phone Finder
        show_header_toggle: false
        entities:
          - entity: script.find_jim_phone
            name: Jim's Phone
            icon: mdi:cellphone
          - entity: script.find_erica_phone
            name: Erica's Phone
            icon: mdi:cellphone

      - type: entity-filter
        entities:
          - entity: person.jim
            image: /local/jim.jpg
          - entity: person.erica
            image: /local/erica.jpg
        state_filter:
          - home
        card:
          type: glance
          title: At Home
          show_state: false
            
      - type: entities
        title: IR Learning
        show_header_toggle: false
        entities:
          - type: call-service
            name: Living Room Learn
            icon: mdi:remote
            service: broadlink.learn
            service_data:
              host: 10.0.0.11
          - type: call-service
            name: Master BR Learn
            icon: mdi:remote
            service: broadlink.learn
            service_data:
              host: 10.0.0.4
          - type: call-service
            name: Guest BR Learn
            icon: mdi:remote
            service: broadlink.learn
            service_data:
              host: 10.0.0.31
          - type: call-service
            name: Office Learn
            service: broadlink.learn
            icon: mdi:remote
            service_data:
              host: 10.0.0.30
          - type: call-service
            name: Fourth BR Learn
            service: broadlink.learn
            icon: mdi:remote
            service_data:
              host: 10.0.0.40
            
      - type: entities
        title: Zigbee Setup
        show_header_toggle: false
        entities:
          - type: call-service
            name: Add Xiaomi Device
            service: xiaomi_aqara.add_device
            service_data:
              gw_mac: !secret xiaomi1_mac
          - entity: switch.zigbee_debug
            name: Zigbee Debug Logging