title: Home Assistant Frontend
views:
  - title: Lights
    icon: mdi:home
    cards:
      - type: glance
        title: Living Room
        entities:
          - entity:  lock.assa_abloy_yale_push_button_deadbolt_yrd110_locked_2
            name: Lock
            tap_action:
              action: toggle
          - entity: media_player.living_room_tv
            name: TV
            tap_action:
              action: toggle
          - entity: light.living_room_lamps
            name: Lamps
            tap_action:
              action: toggle
          - entity: light.piano_led
            name: PianoLED
            tap_action:
              action: toggle
          - entity: light.stairs_led
            name: Stairs
            tap_action:
              action: toggle
          - entity: light.dining_room_light
            name: Dining
            tap_action:
              action: toggle
          - entity: light.piano_plug
            icon: mdi:power-socket-us
            name: "Piano"
            tap_action:
              action: toggle
          - entity: switch.centralite_outlet_2
            icon: mdi:power-socket-us
            name: "Couch"
            tap_action:
              action: toggle
          - entity: switch.hank_hkzw_so03_smart_plug_switch
            icon: mdi:power-socket-us
            name: "Scent"
            tap_action:
              action: toggle
      - type: glance
        title: Kitchen
        entities:
          - entity: light.kitchen_lights
            name: Lights
            tap_action:
              action: toggle
          - entity: vacuum.xiaomi_vacuum_cleaner
            name: Vacuum
          - entity: switch.tradfri_outlet_2
            icon: mdi:power-socket-us
            name: "Scent"
            tap_action:
              action: toggle
          - entity: switch.hank_hkzw_so03_smart_plug_switch_2
            icon: mdi:power-socket-us
            name: "Rice"
            tap_action:
              action: toggle
          - entity: switch.centralite_outlet_1
            icon: mdi:power-socket-us
            name: "Kettle"
            tap_action:
              action: toggle
      - type: glance
        title: Master Bedroom
        entities:
          - entity: media_player.master_bedroom_tv
            name: "TV"
            tap_action:
              action: toggle
          - entity: light.master_bedroom_fixture
            name: "Fixture"
            tap_action:
              action: toggle
          - entity: light.jim_night_lamp
            name: "Jim"
            tap_action:
              action: toggle
          - entity: light.erica_night_lamp
            name: "Erica"
            tap_action:
              action: toggle
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - entity: light.office_lights
            name: Lights
      - type: entities
        title: Guest Bedroom
        show_header_toggle: false
        entities:
          - entity: media_player.guest_bedroom_tv
            name: TV
      - type: entities
        title: Fourth Bedroom
        show_header_toggle: false
        entities:
          - entity: light.fourth_bedroom_fixture
            name: Light
      - type: entities
        title: Basement
        show_header_toggle: false
        entities: 
          - entity: media_player.basement_tv
            name: TV
          - entity: light.basement_staircase_light
            name: Staircase
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - entity: switch.fortrezz_mimolite_switch
            name: Garage Door Switch
          - entity: binary_sensor.garage_sensor
            name: Garage Door Sensor

  - title: Outside
    icon: mdi:weather-sunny
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: light.driveway
            name: "Driveway Light"
          - entity: light.front_garden
            name: "Front Garden Lights"
          - light.porch_light
          - light.deck_light
      - type: entities
        title: Speakers
        show_header_toggle: false
        entities:
          - entity: media_player.backyard_speaker
        
          
  - title: Climate
    icon: mdi:thermometer-lines
    cards:
    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Heating"
      card:
        type: thermostat
        entity:  climate.linear_gc_tbz48_battery_powered_z_wave_thermostat_heating_1
        name: Oil Heater

    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Cooling"
      card:
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity:  climate.dining_room_ac
                name: Dining Room
              - type: thermostat
                entity:  climate.master_bedroom_ac
                name: Master Bedroom
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity:  climate.guest_bedroom_ac
                name: Guest Bedroom
              - type: thermostat
                entity:  climate.fourth_bedroom_ac
                name: Fourth Bedroom
      
    - type: glance
      title: Temperature
      entities:
        - entity: sensor.garage_temperature
          name: Garage
        - entity: sensor.temperature_158d0001d6f386
          name: Downstairs
        - entity: sensor.front_door_temperature
          name: Front Door
        - entity: sensor.temperature_158d000245a6a2
          name: Master BR
        - entity: sensor.temperature_158d000245ae4b
          name: Office
        - entity: sensor.temperature_158d00023cf8f7
          name: Guest BR
        - entity: sensor.temperature_158d00023cf950
          name: Upstairs

  - title: Batteries
    icon: mdi:battery-charging
    cards:
    - type: entities
      title: Battery Levels
      show_header_toggle: false
      entities:
        - type: section
          label: Temperature
        - entity: sensor.downstairs_temperature_battery
        - entity: sensor.master_bedroom_temperature_battery
        - entity: sensor.office_temperature_battery
        - entity: sensor.guest_bedroom_temperature_battery
        - type: section
          label: Door
        - entity: sensor.fridge_door_battery
        - type: section
          label: Button
        - entity: sensor.living_button_battery
        - entity: sensor.master_bedroom_button_battery
        - type: section
          label: Motion
        - entity: sensor.hallway_motion_battery
        - entity: sensor.landing_motion_battery
        - entity: sensor.office_motion_battery
        - type: section
          label: Water
        - entity: sensor.basement_water_battery
        
  - title: Config
    icon: mdi:settings
    cards:
    - type: entities
      title: Configuration
      show_header_toggle: false
      entities:
        - input_select.thermostat_mode
        - entity: input_boolean.sleep_mode
          name: Sleep Mode
          icon: mdi:sleep
        - entity: input_boolean.guest_mode
          name: Guest Mode
        
  - title: Advanced
    icon: mdi:android-debug-bridge
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: script.generate_grocery_list
            name: Generate Mealplan
            tap_action: call_service
            service: script.turn_on
          
          - type: entity-button
            entity: script.archive_mealplan
            name: Archive Mealplan
            tap_action: call_service
            service: script.turn_on

      - type: entity-filter
        entities:
          - entity: person.jim
            image: /local/jim.jpg
          - entity: person.erica
            image: /local/erica.jpg
        state_filter:
          - home
        card:
          type: glance
          title: At Home
          show_state: false
            
      - type: entities
        title: IR Learning
        show_header_toggle: false
        entities:
          - type: call-service
            name: Living Room Learn
            service: switch.broadlink_learn_command_10_0_0_11
          - type: call-service
            name: Master BR Learn
            service: switch.broadlink_learn_command_10_0_0_4
            
      - type: entities
        title: Zigbee Setup
        show_header_toggle: false
        entities:
          - type: call-service
            name: Add Xiaomi Device
            service: xiaomi_aqara.add_device
            service_data:
              gw_mac: !secret xiaomi1_mac
          - entity: switch.zigbee_debug
            name: Zigbee Debug Logging