title: Home Assistant Frontend
views:
  - type: entities
    title: Lights
    entities:
      - type: section
        label: Front Yard
      - light.driveway_light
      - light.front_garden_lights
      - light.porch_light
      - type: section
        label: First Floor
      - light.living_room_lamps
      - light.piano_led
      - light.first_floor_staircase_led
      - group.living_room_christmas_lights
      - light.dining_room_light
      - light.kitchen_lights
      - type: section
        label: Second Floor
      - light.hallway_lights
      - light.master_bedroom_fixture
      - light.jim_night_lamp
      - light.erica_night_lamp
      - light.office_lights
      - type: section
        label: Basement
      - light.basement_staircase_light
      - type: section
        label: Back Yard
      - light.deck_light
      - switch.backyard_string_lights
      
  - type: thermostat
    entity: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
    name: Oil Heater
    
  - type: glance
    title: Climate
    entities:
      - sensor.garage_temperature
      - switch.dining_room_ac
      - sensor.temperature_158d0001d6f386
      - sensor.front_door_temperature
      - climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
      - switch.master_bedroom_ac
      - sensor.temperature_158d000245a6a2
      - sensor.temperature_158d000245ae4b
      - sensor.temperature_158d00023cf8f7
      - sensor.temperature_158d00023cf950

  - type: entities
    title: TVs
    entities:
      - entity: media_player.living_room_tv
      - entity: media_player.master_bedroom_tv

  - type: entities:
    title: Speakers
    entities:
      - entity: media_player.backyard_speaker
      
