- platform: template
  sensors:
    dryer_running:
      friendly_name: "Dryer Running"
      device_class: power
      value_template: "{{ states('sensor.dryer_outlet_power')|float > 100.0 }}"
    washer_running:
      friendly_name: "Washer Running"
      device_class: power
      value_template: "{{ states('sensor.laundry_outlet_power')|float > 100.0 }}"