- platform: mqtt
  state_topic: "smartthings/front_door_sensor/contact"
  payload_on: "open"
  payload_off: "closed"

- platform: mqtt
  state_topic: "smartthings/garage_sensor/contact"
  payload_on: "open"
  payload_off: "closed"