- platform: mqtt
  name: "Front Door Sensor"
  state_topic: "smartthings/front_door_sensor/contact"
  payload_on: "open"
  payload_off: "closed"

- platform: mqtt
  name: "Garage Sensor"
  state_topic: "smartthings/garage_sensor/contact"
  payload_on: "open"
  payload_off: "closed"