- platform: group
  name: Master Bedroom Fixture
  entities:
    - light.master_bedroom_fixture_1
    - light.master_bedroom_fixture_2

- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2

- platform: group
  name: Hallway Lights
  entities:
    - light.hallway_fixture
    - light.hallway_wall_light

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_fixture
    - light.kitchen_high_hats

- platform: group
  name: Fourth Bedroom Fixture
  entities:
    - light.fourth_bedroom_fixture_1
    - light.fourth_bedroom_fixture_2

- platform: group
  name: manual_off_lights
  entities:
    - light.master_bedroom_fixture
    - light.living_room_lamps
    - light.porch_light
    - light.kitchen_lights
    - light.dining_room_light_2
    - light.gateway_light_34ce008dcec1
    - light.driveway_light
    - light.deck_light
    - light.office_lights
    - light.jim_night_lamp
    - light.erica_night_lamp
    - light.piano_led
    - light.fourth_bedroom_fixture