- platform: group
  name: Master Bedroom Fixture
  entities:
    - light.master_bedroom_fixture_1
    - light.master_bedroom_fixture_2

- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2

- platform: group
  name: Hallway Lights
  entities:
    - light.cree_connected_a_19_60w_equivalent_fe040989_10
    - light.cree_connected_a_19_60w_equivalent_fe0409f4_10

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_fixture
    - light.kitchen_high_hats

- platform: group
  name: Fourth Bedroom Fixture
  entities:
    - light.sengled_e11_g13_0316b7c9_1
    - light.sengled_e11_g13_03152cef_1

- platform: group
  name: manual_off_lights
  entities:
    - light.master_bedroom_fixture
    - light.living_room_lamps
    - light.cree_connected_a_19_60w_equivalent_fe041885_10
    - light.kitchen_lights
    - light.dining_room_light
    - light.gateway_light_34ce008dcec1
    - light.osram_lightify_par38_on_off_dim_00a5ee30_3
    - light.cree_connected_a_19_60w_equivalent_fe06e97f_10
    - switch.third_reality_inc_3rss007z_ffe01818_1_6
    - light.jim_night_lamp
    - light.erica_night_lamp
    - light.piano_led
    - light.fourth_bedroom_fixture