- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_fixture
    - light.kitchen_hi_hats

- platform: group
  name: Garage Lights
  entities:
    - light.garage_back_light
    - light.garage_front_light

- platform: group
  name: Backyard Lights
  entities:
    - light.backyard_flood_lights_zha_group_0x0006
    - light.backyard_fence_lights_2
    - light.ledvance_outdoor_accent_light_rgb_23840700_level_light_color_on_off