- platform: group
  name: Master Bedroom Fixture
  entities:
    - light.master_bedroom_fixture_1
    - light.master_bedroom_fixture_2

- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2

- platform: group
  name: Hallway Lights
  entities:
    - light.cree_connected_a_19_60w_equivalent_fe040989_10
    - light.cree_connected_a_19_60w_equivalent_fe0409f4_10

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_fixture
    - light.kitchen_high_hats

- platform: group
  name: Fourth Bedroom Fixture
  entities:
    - light.sengled_e11_g13_0316b7c9_1
    - light.sengled_e11_g13_03152cef_1
    
- platform: group
  name: Kitchen Cabinet Lights
  entities:
    - light.ledvance_edge_lit_under_cabinet_tw_0002c70d_1
    - light.ledvance_edge_lit_under_cabinet_tw_0002c7f4_1
    - light.ledvance_edge_lit_under_cabinet_tw_0002c5ae_1

- platform: group
  name: manual_off_lights
  entities:
    - light.master_bedroom_fixture
    - light.living_room_lamps
    - light.osram_lightify_a19_on_off_dim_10_year_20eb0d00_level_on_off
    - light.kitchen_lights
    - light.dining_room_light
    - light.gateway_light_34ce008dcec1
    - light.osram_lightify_par38_on_off_dim_00a5ee30_3
    - light.cree_connected_a_19_60w_equivalent_fe06e97f_10
    - light.office_lights
    - light.jim_night_lamp
    - light.erica_night_lamp
    - light.piano_led
    - light.fourth_bedroom_fixture
    - light.master_bedroom_closet_lights
    - light.front_garage_light
    - light.master_bedroom_mirror_led

- platform: group
  name: master_bedroom_closet_lights
  entities: 
    - light.sengled_e11_g13_b02c1503_1
    - light.sengled_e11_g13_befa1603_1

- platform: group
  name: grill_light_fixture
  entities:
    - light.cree_connected_a_19_60w_equivalent_72cc09fe_level_on_off
    - light.cree_connected_a_19_60w_equivalent_d4cc09fe_level_on_off