- platform: mqtt
  name: "Hallway Fixture"
  state_topic: "smartthings/hallway_fixture/switch"
  command_topic: "smartthings/hallway_fixture/switch"
  brightness_state_topic: "smartthings/hallway_fixture/level"
  brightness_command_topic: "smartthings/hallway_fixture/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Hallway Wall Light"
  state_topic: "smartthings/hallway_wall_light/switch"
  command_topic: "smartthings/hallway_wall_light/switch"
  brightness_state_topic: "smartthings/hallway_wall_light/level"
  brightness_command_topic: "smartthings/hallway_wall_light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Porch Light"
  state_topic: "smartthings/porch_light/switch"
  command_topic: "smartthings/porch_light/switch"
  brightness_state_topic: "smartthings/porch_light/level"
  brightness_command_topic: "smartthings/porch_light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Basement Staircase Light"
  state_topic: "smartthings/basement_staircase_light/switch"
  command_topic: "smartthings/basement_staircase_light/switch"
  brightness_state_topic: "smartthings/basement_staircase_light/level"
  brightness_command_topic: "smartthings/basement_staircase_light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Deck Light"
  state_topic: "smartthings/deck_light/switch"
  command_topic: "smartthings/deck_light/switch"
  brightness_state_topic: "smartthings/deck_light/level"
  brightness_command_topic: "smartthings/deck_light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Front Garden Lights"
  state_topic: "smartthings/front_garden_lights/switch"
  command_topic: "smartthings/front_garden_lights/switch"
  brightness_state_topic: "smartthings/front_garden_lights/level"
  brightness_command_topic: "smartthings/front_garden_lights/level"
  hs_command_topic: "smartthings/front_garden_lights/color"
  hs_state_topic: "smartthings/front_garden_lights/color"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Kitchen Fixture"
  state_topic: "smartthings/kitchen_fixture/switch"
  command_topic: "smartthings/kitchen_fixture/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Office Lights"
  state_topic: "smartthings/office_lights/switch"
  command_topic: "smartthings/office_lights/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "First Floor Staircase LED"
  state_topic: "smartthings/first_floor_staircase_led/switch"
  command_topic: "smartthings/first_floor_staircase_led/switch"
  brightness_state_topic: "smartthings/first_floor_staircase_led/level"
  brightness_command_topic: "smartthings/first_floor_staircase_led/level"
  hs_command_topic: "smartthings/first_floor_staircase_led/color"
  hs_state_topic: "smartthings/first_floor_staircase_led/color"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Driveway Light"
  state_topic: "smartthings/driveway_light/switch"
  command_topic: "smartthings/driveway_light/switch"
  brightness_state_topic: "smartthings/driveway_light/level"
  brightness_command_topic: "smartthings/driveway_light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Fourth Bedroom Fixture 1"
  state_topic: "smartthings/fourth_bedroom_fixture_1/switch"
  command_topic: "smartthings/fourth_bedroom_fixture_1/switch"
  brightness_state_topic: "smartthings/fourth_bedroom_fixture_1/level"
  brightness_command_topic: "smartthings/fourth_bedroom_fixture_1/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Fourth Bedroom Fixture 2"
  state_topic: "smartthings/fourth_bedroom_fixture_2/switch"
  command_topic: "smartthings/fourth_bedroom_fixture_2/switch"
  brightness_state_topic: "smartthings/fourth_bedroom_fixture_2/level"
  brightness_command_topic: "smartthings/fourth_bedroom_fixture_2/level"
  payload_on: "on"
  payload_off: "off"
  retain: true