- platform: switch
  name: Kitchen Fixture
  entity_id: switch.kitchen_fixture_switch
- platform: switch
  name: Office Lights
  entity_id: switch.office_light_switch
- platform: switch
  name: Garage Front Light
  entity_id: switch.front_garage_switch
- platform: switch
  name: Master Bedroom Mirror LED
  entity_id: switch.master_bedroom_led_switch
- platform: switch
  name: Backyard Fence Lights
  entity_id: switch.smart_strip_2
- platform: switch
  name: Kitchen Hi Hats
  entity_id: switch.kitchen_switch
- platform: switch
  name: Garage Back Light
  entity_id: switch.garage_back_switch
  