version: '3'
services:
  bellows_tty:
    image: homeassistant/tinker-homeassistant:2021.7.4
    devices:
      - $TTY_PORT:$TTY_PORT
    volumes:
      - ./backup.txt:/tmp/backup.txt
    entrypoint: bellows
  bellows_ip:
    image: homeassistant/tinker-homeassistant:2021.7.4
    network_mode: host
    volumes:
      - ./backup.txt:/tmp/backup.txt
    entrypoint: bellows