- platform: template
  sensors:
    downstairs_temperature_battery:
      friendly_name: Downstairs Temperature Battery
      value_template: "{{ state_attr('em:downstairs_temperature', 'battery_level') }}"
      device_class: battery
    master_bedroom_temperature_battery:
      friendly_name: Master Bedroom Temperature Battery
      value_template: "{{ state_attr('em:master_bedroom_temperature', 'battery_level') }}"
      device_class: battery
    office_temperature_battery:
      friendly_name: Office Temperature Battery
      value_template: "{{ state_attr('em:office_temperature', 'battery_level') }}"
      device_class: battery
    guest_bedroom_temperature_battery:
      friendly_name: Guest Bedroom Temperature Battery
      value_template: "{{ state_attr('em:guest_bedroom_temperature', 'battery_level') }}"
      device_class: battery
    fridge_door_battery:
      friendly_name: Fridge Door Battery
      value_template: "{{ state_attr('em:kitchen_fridge_sensor', 'battery_level') }}"
      device_class: battery
    landing_motion_battery:
      friendly_name: Landing Motion Battery
      value_template: "{{ state_attr('em:landing_motion_sensor', 'battery_level') }}"
      device_class: battery
    office_motion_battery:
      friendly_name: Office Motion Battery
      value_template: "{{ state_attr('em:office_motion_sensor', 'battery_level') }}"
      device_class: battery
    basement_water_battery:
      friendly_name: Basement Water Battery
      value_template: "{{ state_attr('em:utility_room_water_sensor', 'battery_level') }}"
      device_class: battery
    master_bedroom_closet_button_battery:
      friendly_name: Master Bedroom Closet Button Battery
      value_template: "{{ state_attr('em:master_bedroom_closet_button', 'battery_level') }}"
      device_class: battery
    master_bedroom_button_battery:
      friendly_name: Master Bedroom Bed Button Battery
      value_template: "{{ state_attr('em:master_bedroom_button', 'battery_level') }}"
      device_class: battery