- platform: mqtt
  sensors:
    - name: "Backyard Temperature"
      state_topic: "rtl_433/0302062ee07c/devices/Acurite-Tower/A/3658/temperature_C"
      unit_of_measurement: "°F"
      value_template: "{{ ((value)*9/5) + 32 }}"
