- id: woo_button
  alias: Woo button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: single
  action:
    service: script.rick_flair_woo

- id: goal_horn_button
  alias: Goal horn button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: double
  action:
    service: script.goal_horn

- id: downstairs_hallway_top_button
  alias: Downstairs Hallway Top Button
  trigger:
  - event_data:
      entity_id: zwave.linear_wa00z1_scene_switch
      scene_id: 1
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.hallway_lights

- id: downstairs_hallway_bottom_button
  alias: Downstairs Hallway Bottom Button
  trigger:
  - event_data:
      entity_id: zwave.linear_wa00z1_scene_switch
      scene_id: 2
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_off
      entity_id: light.hallway_lights

- id: upstairs_hallway_top_button
  alias: Upstairs Hallway Top Button
  trigger:
  - event_data:
      entity_id: zwave.linear_wa00z1_scene_switch_2
      scene_id: 1
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.hallway_lights

- id: upstairs_hallway_bottom_button
  alias: Upstairs Hallway Bottom Button
  trigger:
  - event_data:
      entity_id: zwave.linear_wa00z1_scene_switch_2
      scene_id: 2
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_off
      entity_id: light.hallway_lights