- id: nobody_home
  alias: Nobody home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: script.bedtime

- id: somebody_home
  alias: Somebody is home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.living_room_light
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_light
    - service: switch.turn_on
      data:
        entity_id: switch.bedroom_light

- id: kitchen_motion
  alias: Kitchen Motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00016612a5
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_light

- id: kitchen_empty
  alias: Kitchen Empty
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00016612a5
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_light

- id: woo_button
  alias: Woo button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: single
  action:
    service: script.rick_flair_woo

- id: goal_horn_button
  alias: Goal horn button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: double
  action:
    service: script.goal_horn

- id: bedroom_lights_button
  alias: Bedroom lights button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016dbf86
      click_type: single
  action:
    service: switch.toggle
    data:
      entity_id: switch.bedroom_light

- id: bedtime_button
  alias: Bedtime button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016dbf86
      click_type: double
  action:
    service: script.bedtime

- id: devils_gametime
  alias: Devils Gametime
  trigger:
    platform: state
    entity_id: calendar.devils_games
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: script.google_home_sound
    data_template:
      file: "hells_bells.mp3"

- id: living_room_tv_auto_cast
  alias: LR TV auto cast on
  trigger:
    platform: template
    value_template: "{{ not states('media_player.mibox3') in ['off', 'unavailable'] }}"
  condition:
    condition: state
    entity_id: switch.living_room_tv
    state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.living_room_tv
    - service: script.living_room_chromecast_input

- id: bedroom_tv_auto_cast
  alias: BR TV auto cast on
  trigger:
    platform: template
    value_template: "{{ not states('media_player.bedroom_cast') in ['off', 'unavailable'] }}"
  condition:
    condition: state
    entity_id: switch.bedroom_tv
    state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.bedroom_tv

- id: new_voice_assistant_intent
  alias: New Voice Assistant Intent
  trigger:
    platform: mqtt
    topic: 'assistant/+/intent'
  action:
    event: VOICE_ASSISTANT_INTENT
    event_data_template:
      payload: '{{ trigger.payload }}'
      topic: '{{ trigger.topic }}'