- id: woo_button
  alias: Woo button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: single
  action:
    service: script.rick_flair_woo

- id: goal_horn_button
  alias: Goal horn button
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016da2c9
      click_type: double
  action:
    service: script.goal_horn