- platform: template
  sensors:
    downstairs_temperature_battery:
      friendly_name: "Downstairs"
      value_template: "{{ state_attr('sensor.lumi_lumi_weather_01d6f386_1_1026', 'battery_level') }}"
      device_class: battery
    master_bedroom_temperature_battery:
      friendly_name: "Master BR"
      value_template: "{{ state_attr('sensor.lumi_lumi_weather_0245a6a2_1_1026', 'battery_level') }}"
      device_class: battery
    office_temperature_battery:
      friendly_name: "Office"
      value_template: "{{ state_attr('sensor.lumi_lumi_weather_0245ae4b_1_1026', 'battery_level') }}"
      device_class: battery
    guest_bedroom_temperature_battery:
      friendly_name: "Guest BR"
      value_template: "{{ state_attr('sensor.lumi_lumi_weather_023cf8f7_1_1026', 'battery_level') }}"
      device_class: battery
    fridge_door_battery:
      friendly_name: "Fridge"
      value_template: "{{ state_attr('binary_sensor.lumi_lumi_sensor_magnet_aq2_01d3a024_1_6', 'battery_level') }}"
      device_class: battery
    hallway_motion_battery:
      friendly_name: "Hallway"
      value_template: "{{ state_attr('binary_sensor.lumi_lumi_sensor_motion_aq2_016612a5_1_1280', 'battery_level') }}"
      device_class: battery
    landing_motion_battery:
      friendly_name: "Landing"
      value_template: "{{ state_attr('binary_sensor.lumi_lumi_sensor_motion_aq2_02b6fe4e_1_1280', 'battery_level') }}"
      device_class: battery
    office_motion_battery:
      friendly_name: "Office"
      value_template: "{{ state_attr('binary_sensor.lumi_lumi_sensor_motion_aq2_02b95de8_1_1280', 'battery_level') }}"
      device_class: battery
    basement_water_battery:
      friendly_name: "Basement"
      value_template: "{{ state_attr('binary_sensor.lumi_lumi_sensor_wleak_aq1_023a58df_1_1280', 'battery_level') }}"
      device_class: battery