- platform: template
  sensors:
    downstairs_temperature_battery:
      value_template: "{{ state_attr('sensor.temperature_158d0001d6f386', 'battery_level') }}"
      device_class: battery
    master_bedroom_temperature_battery:
      value_template: "{{ state_attr('sensor.temperature_158d000245a6a2', 'battery_level') }}"
      device_class: battery
    office_temperature_battery:
      value_template: "{{ state_attr('sensor.temperature_158d000245ae4b', 'battery_level') }}"
      device_class: battery
    guest_bedroom_temperature_battery:
      value_template: "{{ state_attr('sensor.temperature_158d00023cf8f7', 'battery_level') }}"
      device_class: battery
    fridge_door_battery:
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0001d3a024', 'battery_level') }}"
      device_class: battery
    hallway_motion_battery:
      value_template: "{{ state_attr('binary_sensor.motion_sensor_158d00016612a5', 'battery_level') }}"
      device_class: battery
    landing_motion_battery:
      value_template: "{{ state_attr('binary_sensor.motion_sensor_158d0002b6fe4e', 'battery_level') }}"
      device_class: battery
    office_motion_battery:
      value_template: "{{ state_attr('binary_sensor.motion_sensor_158d0002b95de8', 'battery_level') }}"
      device_class: battery
    basement_water_battery:
      value_template: "{{ state_attr('binary_sensor.water_leak_sensor_158d00023a58df', 'battery_level') }}"
      device_class: battery
    master_bedroom_closet_button_battery:
      value_template: "{{ state_attr('binary_sensor.switch_158d00016da2c9', 'battery_level') }}"
      device_class: battery
    master_bedroom_button_battery:
      value_template: "{{ state_attr('binary_sensor.switch_158d00016dbf86', 'battery_level') }}"
      device_class: battery