- platform: mqtt
  name: "Garage Temperature"
  state_topic: "smartthings/garage_sensor/temperature"
  device_class: "temperature"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Front Door Temperature"
  state_topic: "smartthings/front_door_sensor/temperature"
  device_class: "temperature"
  unit_of_measurement: "°F"