- platform: broadlink
  host: 10.0.0.4
  mac: !secret broadlink1_mac
- platform: broadlink
  host: 10.0.0.11
  mac: !secret broadlink2_mac
- platform: broadlink
  host: 10.0.0.30
  mac: !secret broadlink3_mac
- platform: broadlink
  host: 10.0.0.31
  mac: !secret broadlink4_mac