- platform: broadlink
  host: 10.0.0.4
  mac: !secret broadlink1_mac # Location: Master BR
  switches:
    master_bedroom_ac:
      command_on: !secret pioneer_inverter_ac_on
      command_off: !secret pioneer_inverter_off
    master_bedroom_heat:
      command_on: !secret pioneer_inverter_heat_on
      command_off: !secret pioneer_inverter_off
- platform: broadlink
  host: 10.0.0.11
  mac: !secret broadlink2_mac # Location: Downstairs
  switches:
    dining_room_ac:
      command_on: !secret dining_room_ac_power
      command_off: !secret dining_room_ac_power
- platform: broadlink
  host: 10.0.0.30
  mac: !secret broadlink3_mac # Location: Office
  switches:
    office_ac:
      command_on: !secret pioneer_inverter_ac_on
      command_off: !secret pioneer_inverter_off
    office_heat:
      command_on: !secret pioneer_inverter_heat_on
      command_off: !secret pioneer_inverter_off
- platform: broadlink
  host: 10.0.0.31
  mac: !secret broadlink4_mac # Location:Guest Bedroom
  switches:
    guest_bedroom_ac:
      command_on: !secret pioneer_inverter_ac_on
      command_off: !secret pioneer_inverter_off
    guest_bedroom_heat:
      command_on: !secret pioneer_inverter_heat_on
      command_off: !secret pioneer_inverter_off
- platform: broadlink
  host: 10.0.0.40
  mac: !secret broadlink5_mac # Location: 4th br
  switches:
    fourth_bedroom_ac:
      command_on: !secret fourth_bedroom_ac_power
      command_off: !secret fourth_bedroom_ac_power
- platform: broadlink
  host: 10.0.0.53
  mac: !secret broadlink6_mac # Location: Basement