- platform: mqtt
  name: "Centralite Outlet 1"
  state_topic: "smartthings/centralite_outlet_1/switch"
  command_topic: "smartthings/centralite_outlet_1/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
- platform: mqtt
  name: "Centralite Outlet 2"
  state_topic: "smartthings/centralite_outlet_2/switch"
  command_topic: "smartthings/centralite_outlet_2/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
- platform: mqtt
  name: "Centralite Outlet 3"
  state_topic: "smartthings/centralite_outlet_3/switch"
  command_topic: "smartthings/centralite_outlet_3/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
- platform: mqtt
  name: "Centralite Outlet 4"
  state_topic: "smartthings/centralite_outlet_4/switch"
  command_topic: "smartthings/centralite_outlet_4/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
- platform: mqtt
  name: "Tradfri Outlet 1"
  state_topic: "smartthings/tradfri_outlet_1/switch"
  command_topic: "smartthings/tradfri_outlet_1/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
- platform: mqtt
  name: "Tradfri Outlet 2"
  state_topic: "smartthings/tradfri_outlet_2/switch"
  command_topic: "smartthings/tradfri_outlet_2/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true