- platform: rest
  resource: http://127.0.0.1:8126/container/appdaemon
  name: Appdaemon
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://10.0.0.6:8126/container/zwavejs2mqtt
  name: ZWaveJS
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://10.0.0.6:8126/container/zigbee2mqtt
  name: Zigbee
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'