- platform: bluetooth_tracker
  new_device_defaults:
    track_new_devices: False
    hide_if_away: False
# - platform: asuswrt
#   host: 10.0.0.1
#   username: !secret router_user
#   password: !secret router_password
#   protocol: ssh
#   mode: ap
#   new_device_defaults:
#     track_new_devices: False
#     hide_if_away: False