- platform: nmap_tracker
  hosts:
    - 10.0.0.17
    - 10.0.0.47
    - 10.0.0.4
    - 10.0.0.11
    - 10.0.0.30
    - 10.0.0.31
    - 10.0.0.40
    - 10.0.0.53
  new_device_defaults:
    track_new_devices: True
