- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_fixture
    - light.kitchen_high_hats
    
- platform: group
  name: manual_off_lights
  entities:
    - light.master_bedroom_fixture
    - light.living_room_lamps
    - em:front_porch_light
    - light.kitchen_lights
    - light.dining_room_light
    - light.gateway_light_34ce008dcec1
    - em:driveway_light
    - em:back_deck_light
    - light.office_lights
    - light.jim_night_lamp
    - light.erica_night_lamp
    - light.piano_led
    - light.fourth_bedroom_fixture
    - light.master_bedroom_closet_lights
    - em:front_garage_light
    - em:master_bedroom_mirror_led