- platform: group
  name: Living Room Lamps
  entities:
    - em:living_room_lamp_1
    - em:living_room_lamp_2

- platform: group
  name: Kitchen Lights
  entities:
    - em:kitchen_fixture
    - em:kitchen_high_hats

- platform: group
  name: Backyard Lights
  entities:
    - em:backyard_flood_lights
    - em:backyard_fence_lights
    - em:backyard_bar_lights