- platform: group
  name: Master Bedroom Fixture
  entities:
    - light.master_bedroom_fixture_1
    - light.master_bedroom_fixture_2

- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2

- platform: group
  name: Hallway Lights
  entities:
    - em:hallway_fixture
    - em:hallway_wall_light

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_fixture
    - light.kitchen_high_hats

- platform: group
  name: Fourth Bedroom Fixture
  entities:
    - em:fourth_bedroom_fixture_1
    - em:fourth_bedroom_fixture_2
    
- platform: group
  name: Kitchen Cabinet Lights
  entities:
    - em:kitchen_cabinet_right_light
    - em:kitchen_cabinet_left_light_1
    - em:kitchen_cabinet_left_light_2

- platform: group
  name: manual_off_lights
  entities:
    - light.master_bedroom_fixture
    - light.living_room_lamps
    - em:front_porch_light
    - light.kitchen_lights
    - light.dining_room_light
    - light.gateway_light_34ce008dcec1
    - em:driveway_light
    - em:back_deck_light
    - light.office_lights
    - light.jim_night_lamp
    - light.erica_night_lamp
    - light.piano_led
    - light.fourth_bedroom_fixture
    - light.master_bedroom_closet_lights
    - em:front_garage_light

- platform: group
  name: master_bedroom_closet_lights
  entities: 
    - em:master_bedroom_closet_light_1
    - em:master_bedroom_closet_light_2