- platform: group
  name: Living Room Lamps
  entities:
    - em:living_room_lamp_1
    - em:living_room_lamp_2

- platform: group
  name: Kitchen Lights
  entities:
    - em:kitchen_fixture
    - em:kitchen_high_hats

- platform: group
  name: Backyard Lights
  entities:
    - em:backyard_flood_lights
    - em:backyard_fence_lights
    - em:backyard_bar_lights

- platform: group
  name: manual_off_lights
  entities:
    - em:master_bedroom_fixture
    - em:master_bedroom_mirror_led
    - em:master_bedroom_closet_lights
    - em:jim_night_lamp
    - em:erica_night_lamp
    - em:living_room_lamps
    - em:piano_led
    - em:kitchen_lights
    - em:dining_room_light
    - em:front_porch_light
    - em:driveway_light
    - em:backyard_flood_lights
    - em:backyard_fence_lights
    - em:backyard_bar_lights
    - em:office_lights
    - em:front_garage_light
    - em:fourth_bedroom_fixture
    - em:attic_lights
    - em:basement_lights