- platform: switch
  name: Kitchen High Hats
  entity_id: em:kitchen_high_hat_switch
- platform: switch
  name: Kitchen Fixture
  entity_id: em:kitchen_fixture_switch
- platform: switch
  name: Office Lights
  entity_id: em:office_light_switch
- platform: switch
  name: Front Garage Light
  entity_id: em:front_garage_switch
- platform: switch
  name: Master Bedroom Mirror LED
  entity_id: em:master_bedroom_led_switch
- platform: switch
  name: Backyard Fence Lights
  entity_id: em:aeon_labs_smart_strip_2
