- platform: switch
  name: Kitchen High Hats
  entity_id: em:kitchen_high_hat_switch
- platform: switch
  name: Kitchen Fixture
  entity_id: em:kitchen_fixture_switch
- platform: switch
  name: Office Lights
  entity_id: em:office_light_switch
- platform: switch
  name: Front Garage Light
  entity_id: switch.centralite_3210_l_c9488805_on_off
- platform: switch
  name: Master Bedroom Mirror LED
  entity_id: switch.centralite_3210_l_96312d0b_on_off
- platform: switch
  name: Backyard Fence Lights
  entity_id: switch.aeon_labs_dsc11_smart_strip_switch_2
