title: Stys Home Control
views:
  - title: Lights
    icon: mdi:home
    cards:
      - type: glance
        title: Living Room
        entities:
          - entity:  em:front_entrance_lock
            name: Lock
            tap_action:
              action: toggle
          - entity: em:living_room_tv
            name: TV
            tap_action:
              action: toggle
          - entity: em:living_room_lamps
            name: Lamps
            tap_action:
              action: toggle
          - entity: em:piano_led
            name: PianoLED
            tap_action:
              action: toggle
          - entity: em:first_floor_staircase_led
            name: Stairs
            tap_action:
              action: toggle
          - entity: em:dining_room_light
            name: Dining
            tap_action:
              action: toggle
          - entity: em:piano_power
            icon: mdi:power-socket-us
            name: "Piano"
            tap_action:
              action: toggle
          - entity: em:couch_outlet
            icon: mdi:power-socket-us
            name: "Couch"
            tap_action:
              action: toggle
          - entity: em:living_room_fragrance
            icon: mdi:power-socket-us
            name: "Scent"
            tap_action:
              action: toggle
      - type: glance
        title: Kitchen
        entities:
          - entity: em:kitchen_lights
            name: Lights
            tap_action:
              action: toggle
          - entity: em:kitchen_cabinet_lights
            name: Cabinets
            tap_action:
              action: toggle
          - entity: em:robot_vacuum
            name: Vacuum
          - entity: em:kitchen_fragrance
            icon: mdi:power-socket-us
            name: "Scent"
            tap_action:
              action: toggle
          - entity: em:rice_cooker
            icon: mdi:power-socket-us
            name: "Rice"
            tap_action:
              action: toggle
          - entity: em:espresso_machine
            icon: mdi:power-socket-us
            name: "Espresso"
            tap_action:
              action: toggle
          - entity: em:kitchen_fridge_sensor
            name: Fridge
      - type: glance
        title: Master Bedroom
        entities:
          - entity: em:master_bedroom_tv
            name: "TV"
            tap_action:
              action: toggle
          - entity: em:master_bedroom_fixture
            name: "Fixture"
            tap_action:
              action: toggle
          - entity: em:jim_night_lamp
            name: "Jim"
            tap_action:
              action: toggle
          - entity: em:erica_night_lamp
            name: "Erica"
            tap_action:
              action: toggle
      - type: glance
        title: Office
        entities:
          - entity: climate.office_ac
            name: AC
          - entity: em:office_lights
            name: Lights
            tap_action:
              action: toggle
      - type: glance
        title: Guest Bedroom
        entities:
          - entity: em:guest_bedroom_tv
            name: TV
            tap_action:
              action: toggle
      - type: glance
        title: Fourth Bedroom
        entities:
          - entity: em:fourth_bedroom_fixture
            name: Light
            tap_action:
              action: toggle
      - type: glance
        title: Basement
        entities: 
          - entity: em:basement_tv
            name: TV
            tap_action:
              action: toggle
          - entity: em:landing_light
            name: Staircase
            tap_action:
              action: toggle
          - entity: em:utility_room_water_sensor
            name: Water Sensor
          - entity: binary_sensor.washer_running
            name: Washer
          - entity: binary_sensor.dryer_running
            name: Dryer
      - type: glance
        title: Garage
        entities:
          - entity: em:garage_door_switch
            name: Garage Door Switch
            tap_action:
              action: toggle
          - entity: em:garage_door_sensor
            name: Garage Door Sensor
          - entity: em:front_garage_light
            name: Front Light
            tap_action:
              action: toggle

  - title: Outside
    icon: mdi:weather-sunny
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: glance
        title: Backyard
        entities:
          - entity: em:backyard_speaker
            name: Speakers
          - entity: em:back_deck_light
            name: Deck
            tap_action:
              action: toggle
      - type: glance
        title: Frontyard
        entities:
          - entity: em:driveway_light
            name: Driveway
            tap_action:
              action: toggle
          - entity: em:front_garden_lights
            name: Garden
            tap_action:
              action: toggle
          - entity: em:front_porch_light
            name: Porch
            tap_action:
              action: toggle
          
  - title: Climate
    icon: mdi:thermometer-lines
    cards:
    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Heating"
      card:
        type: thermostat
        entity: em:oil_thermostat
        name: Oil Heater

    - type: conditional
      conditions:
        - entity: input_select.thermostat_mode
          state: "Cooling"
      card:
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity:  climate.dining_room_ac
                name: Dining Room
              - type: thermostat
                entity:  climate.master_bedroom_ac
                name: Master Bedroom
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity:  climate.guest_bedroom_ac
                name: Guest Bedroom
              - type: thermostat
                entity:  climate.fourth_bedroom_ac
                name: Fourth Bedroom
      
    - type: glance
      title: Temperature
      entities:
        - entity: em:garage_temperature
          name: Garage
        - entity: em:downstairs_temperature
          name: Downstairs
        - entity: em:front_door_temperature
          name: Front Door
        - entity: em:master_bedroom_temperature
          name: Master BR
        - entity: em:office_temperature
          name: Office
        - entity: em:guest_bedroom_temperature
          name: Guest BR
        - entity: em:upstairs_temperature
          name: Upstairs

    - type: glance
      title: Humidity
      entities:
        - entity: em:downstairs_humidity
          name: Downstairs
        - entity: em:master_bedroom_humidity
          name: Master BR
        - entity: em:office_humidity
          name: Office
        - entity: em:guest_bedroom_humidity
          name: Guest BR
        - entity: em:upstairs_humidity
          name: Upstairs

  - title: Batteries
    icon: mdi:battery-charging
    cards:
    - type: entities
      title: Battery Levels
      show_header_toggle: false
      entities:
        - type: section
          label: Temperature
        - entity: sensor.downstairs_temperature_battery
        - entity: sensor.master_bedroom_temperature_battery
        - entity: sensor.office_temperature_battery
        - entity: sensor.guest_bedroom_temperature_battery
        - type: section
          label: Door
        - entity: sensor.fridge_door_battery
        - type: section
          label: Button
        - entity: sensor.living_button_battery
        - entity: sensor.master_bedroom_button_battery
        - type: section
          label: Motion
        - entity: sensor.hallway_motion_battery
        - entity: sensor.landing_motion_battery
        - entity: sensor.office_motion_battery
        - type: section
          label: Water
        - entity: sensor.basement_water_battery
        
  - title: Config
    icon: mdi:settings
    cards:
    - type: entities
      title: Configuration
      show_header_toggle: false
      entities:
        - input_select.thermostat_mode
        - entity: input_boolean.sleep_mode
          name: Sleep Mode
          icon: mdi:sleep
        - entity: input_boolean.guest_mode
          name: Guest Mode
        
  - title: Advanced
    icon: mdi:android-debug-bridge
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: script.generate_grocery_list
            name: Generate Mealplan
            tap_action: call_service
            service: script.turn_on
          
          - type: entity-button
            entity: script.archive_mealplan
            name: Archive Mealplan
            tap_action: call_service
            service: script.turn_on

      - type: entity-filter
        entities:
          - entity: person.jim
            image: /local/jim.jpg
          - entity: person.erica
            image: /local/erica.jpg
        state_filter:
          - home
        card:
          type: glance
          title: At Home
          show_state: false
            
      - type: entities
        title: IR Learning
        show_header_toggle: false
        entities:
          - type: call-service
            name: Living Room Learn
            service: switch.broadlink_learn_command_10_0_0_11
          - type: call-service
            name: Master BR Learn
            service: switch.broadlink_learn_command_10_0_0_4
            
      - type: entities
        title: Zigbee Setup
        show_header_toggle: false
        entities:
          - entity: switch.zigbee_debug
            name: Zigbee Debug Logging