- platform: universal
  name: Living Room TV
  children:
    - em:living_room_speaker
    - em:living_room_shield
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: em:living_room_vizio_tv
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: em:living_room_vizio_tv
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: em:living_room_vizio_tv
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: em:living_room_vizio_tv
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id: em:living_room_vizio_tv
        is_volume_muted: '{{ is_volume_muted }}'
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: em:living_room_vizio_tv
        source: '{{ source }}'
  attributes:
    state: em:living_room_vizio_tv
    is_volume_muted: em:living_room_vizio_tv|is_volume_muted
    volume_level: em:living_room_vizio_tv|volume_level
    source: em:living_room_vizio_tv|source
    source_list: em:living_room_vizio_tv|source_list

- platform: universal
  name: Master Bedroom TV
  children:
    - em:master_bedroom_gtv
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: em:master_bedroom_vizio_tv
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: em:master_bedroom_vizio_tv
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: em:master_bedroom_vizio_tv
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: em:master_bedroom_vizio_tv
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id: em:master_bedroom_vizio_tv
        is_volume_muted: '{{ is_volume_muted }}'
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: em:master_bedroom_vizio_tv
        source: '{{ source }}'
  attributes:
    state: em:master_bedroom_vizio_tv
    is_volume_muted: em:master_bedroom_vizio_tv|is_volume_muted
    volume_level: em:master_bedroom_vizio_tv|volume_level
    source: em:master_bedroom_vizio_tv|source
    source_list: em:master_bedroom_vizio_tv|source_list
    
- platform: universal
  name: Basement TV
  children:
    - em:basement_mibox
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.basement_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.basement_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.basement_tv_volume_mute
  attributes:
    state: input_boolean.basement_tv
    
- platform: universal
  name: Guest Bedroom TV
  children:
    - em:guest_bedroom_mibox
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.guest_bedroom_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.guest_bedroom_tv
    volume_up:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_up
    volume_down:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_down
    volume_mute:
      service: script.turn_on
      data:
        entity_id: script.guest_bedroom_tv_volume_mute
  attributes:
    state: input_boolean.guest_bedroom_tv