- platform: broadlink
  host: 10.0.0.4
  mac: !secret broadlink1_mac
  type: rm_mini
  timeout: 20
  name: Master Bedroom Broadlink

- platform: broadlink
  host: 10.0.0.11
  mac: !secret broadlink2_mac
  type: rm_mini
  timeout: 20
  name: Downstairs Broadlink

- platform: broadlink
  host: 10.0.0.30
  mac: !secret broadlink3_mac
  type: rm_mini
  timeout: 20
  name: Office Broadlink

- platform: broadlink
  host: 10.0.0.31
  mac: !secret broadlink4_mac
  type: rm_mini
  timeout: 20
  name: Guest Bedroom Broadlink

- platform: broadlink
  host: 10.0.0.40
  mac: !secret broadlink5_mac
  type: rm_mini
  timeout: 20
  name: Fourth Bedroom Broadlink

- platform: broadlink
  host: 10.0.0.53
  mac: !secret broadlink6_mac
  type: rm_mini
  timeout: 20
  name: Basement Broadlink