# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false

devices: devices.yaml

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost:1883'
  user: 'zigbee2mqtt'
  password: 'zigbee2mqtt'
  client_id: 'zigbee2mqtt'

# Serial settings
serial:
  adapter: ezsp
  port: 'tcp://10.0.0.63:8888'

frontend:
  # Optional, default 8080
  port: 8080
  # Optional, default 0.0.0.0
  host: 0.0.0.0