# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false

advanced:
  availability_timeout: 0
  last_seen: 'ISO_8601_local'
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false

ota:
  disable_automatic_update_check: true

devices: devices.yaml
groups: groups.yaml

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost:1883'
  user: 'zigbee2mqtt'
  password: 'zigbee2mqtt'
  client_id: 'zigbee2mqtt'

# Serial settings
serial:
  port: /dev/ttyUSB2

frontend:
  # Optional, default 8080
  port: 8080
  # Optional, default 0.0.0.0
  host: 0.0.0.0