# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: zigbee2mqtt

# Serial settings
serial:
  adapter: ezsp
  port: 'tcp://10.0.0.63:8888'